### ISSUE TITLE
Lecture Capture: automatically upload from capture machines to S3

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#100]
As the technical services manager, I want lecture capture videos to be automatically uploaded from the 1Beyond capture machines into a S3 bucket where they can be processed by OVS. 

We will write a script that will be run periodically (probably daily, after other 1Beyonds tasks are done) on the 1Beyond systems to upload videos to a S3 bucket that OVS will watch and process (see #101) 

### acceptance criteria
- [x]  Notify DevOps on any failure to upload (OpsGenie? Sentry?)
- [ ] Script needs to be configurable by the technical services manager so that necessary info is embedded in the file name, namely:
  - [ ] Collection name = course number + section number
  - [ ] datetime
  - [ ] room number? (useful because it can be used to identify the 1Beyond machine involved, if there is a failure)
- [ ] on success, remove local copies of video files

### questions
- [ ] How many lectures can we store on the 1Beyond before storage becomes a problem?

**Comment by mbertrand** [comment]
`on success, remove local copies of video files`: success == uploaded to S3? Or uploaded to S3 and imported/transcoded by OVS?

**Comment by MITTechTV** [comment]
File name metadata also need course section number (ie, L01, L02, etc) for proper authentication with Moira lists in Stellar as some courses do multiple sections and restrict access to particular section number.

**Comment by pdpinch** [comment]
Thanks Elaine. Let me suggest that we combine course number and section number into the collection name. 

I've updated the description to include this change.

**Comment by shaidar** [comment]
#### File Upload
This is the main piece and based on initial assessment, we will be using [aws s3 sync](http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) to sync files between the local folder (U-Switch_Records_Done) and the S3 bucket. Haven't decided yet on whether to run this on a scheduled basis or to watch the folder for changes and trigger the script, but if we're sticking with the way things are currently setup, it'll be a scheduled task.

#### Notifications & Logging
- Notifications on failure will be sent to a DevOps slack channel to investigate.
- Log script actions locally on the machine to a log file.

#### Dependencies
- Python 3.6.2
- AWS CLI

#### Challenges
- Secrets management
- Possible manual work to install dependencies on lecture capture machines

#### Testing
- Will setup a VM and verify initial assumptions
- Run script in parallel on one of the hosts to debug and test
- Deploy dependencies and script on remaining hosts

**Comment by shaidar** [comment]
After meeting with team, it was decided to have the script only upload files from the 'done' folder to the s3 bucket without doing any filename manipulation.
