### ISSUE TITLE
Lecture Capture: parse S3 watch folder for new videos

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#101]
As the technical services manager, I want lecture capture videos to be ingested into the OVS system and have transcoding started automatically. 

We will write a periodic task in OVS that checks for files in the S3 watch folder that the 1Beyond machines upload video to (see #100). For any files that exist in the bucket, the script will attempt to create a corresponding video object in OVS and start the transcode process. The created video object will be matched to an existing collection, or a new collection will be created. 

### Acceptance criteria
- [x] Alert DevOps on any error (OpsGenie? Sentry?)
- [x] create a video object for each video file encountered
  - [x] if the video doesn't match any existing collection, create one, owned by the user with the e-mail specified in`LECTURE_CAPTUR_USER`
- [x] After the video object is successfully created and the video is moved from the S3 watch bucket to the S3 upload bucket, it can be removed from the S3 watch bucket. This will allow us to treat the S3 watch bucket as a queue of sorts. 
- [ ] Turn on S3 versioning in the bucket, to avoid any accidental data loss.

**Comment by mbertrand** [comment]
- Which user should be the owner of the video? The admin account?
- OVS currently keeps all original uploaded videos.  Instead of deleting the video from the bucket, how about moving it from the S3 watch folder to the standard upload bucket used by OVS?
- What will S3 versioning be used for?

**Comment by pdpinch** [comment]
- When we add channels (#51), we can change ownership of a video from a user to a channel. Channels can be administrated by the user who created the channel, or the members of a moira list (#52) 
- My intention for deleting videos was that they would be deleted from the watch bucket. We're using the watch bucket as a queue. 
- S3 Versioning is just an easy way to get backups on the S3 buckets. It's important that we don't lose any of these irreplaceable video files. We may reconsider the specifics once we understand the cost implications. 

I've updated the description to try to reflect these answers.

**Comment by pdpinch** [comment]
Take a look at S3 lifecycle events, so OVS can respond whenever an upload is completed, instead of reading the files in the S3 watch folder.

**Comment by mbertrand** [comment]
I'm working on the approach of sending S3 Lifecycle SNS notifications to an OVS endpoint

Setting this up requires the following in AWS:
  - Create an SNS topic
  - Subscribe to the SNS topic, using HTTPS protocol and the endpoint being `https://<domain>/api/v0/s3event/`
  - The endpoint needs to be able to handle the subscription confirmation request from AWS, and either auto-confirm by getting the supplied `SubscribeURL` in the message, or mailing admins with that URL for manual confirmation. 
  - A notification event needs to be created for the S3 watch bucket, with the event type being `ObjectCreate (All)`, to be sent to the SNS topic create above

Questions:
- @shaidar and @blarghmatey should the app do the above setup steps via `boto3` in a django management command?  And do you have a preference on whether the subscription confirmation is handled automatically or manually?
- Should a video from the watch bucket be deleted after it is successfully copied to the OVS upload bucket and model objects are created for it, or only after it is successfully transcoded?
- Should the endpoint be HTTP or HTTPS? 
   >"Amazon SNS will only deliver messages to HTTPS endpoints that have a signed certificate from a trusted CA that Amazon SNS recognizes."
- What kind of authentication to use to make sure the endpoint is receiving a legitimate notification from AWS?  Options:
  - [Verify the message signature](http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.verify.signature.html)
  - Store the Topic ARN in settings and make sure it matches the one sent by SNS
  - If using HTTPS for the endpoint, basic access authentication can be used (username/password)

**Comment by pdpinch** [comment]
After further discussion, we decided to focus on the celery approach first, since even if we use SNS we still want a periodic check of the S3 bucket for any re-queued failed files.

**Comment by mbertrand** [comment]
### Matching filenames to collections
- Each incoming filename currently includes the course #, session, and recording date.  This may change to also include a semester and year.  If not, semester and year will have to be deduced from the recording date.
- The collection title should match the format `course#-session-semester-year`
- There will be a `LECTURE_CAPTURE_USER` set to Elaine's email address
- For each file in the S3 bucket, the filename will be parsed to extract the required info, and matched to the collection that has the matching title and is owned/created by the user specified in `LECTURE_CAPTURE_USER`.  If no matching collection is found, it will be created.

**Comment by Ferdi** [comment]
Great, I think file names should include course# + year + semester

**Comment by emmello** [comment]
Just a note that course numbers can be alpha numeric - ie, 1.271, HST.969, STS.001 or 7.S939  - first digit is the Subject number.   http://student.mit.edu/catalog/index.cgi

**Comment by giocalitri** [comment]
IMHO relying on hardcoded logic is not an optimal solution for the problem.
Still IMHO, at this point it is better to include the collection key in the file name created by the box.

**Comment by pdpinch** [comment]
I updated the description to match current naming (collections, not channels), the use of celery and not S3 Lifecyle events, and the collection-matching scheme described in https://github.com/mitodl/odl-video-service/issues/101#issuecomment-321003238.
