### ISSUE TITLE
Can't upload more than 5 files from dropbox

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#1027]
### Steps to Reproduce

1. Create a new collection
2. Upload the 32 videos from https://www.dropbox.com/sh/27n8kzccjxv7dm1/AADn0oY1V2gjjZXkbuP8gu_Sa?dl=0

### Expected Behavior

- All 32 videos get queued for transcode

### Actual Behavior

- Only 5 videos got queued
- I have to reload the page to see what's been queued

**Comment by pdpinch** [comment]
The number of videos that get queued seems to be variable. On a subsequent attempt, I uploaded 16 and 7 were queued.

**Comment by pdpinch** [comment]
No apparent errors in Sentry, but when I watch in my browser, I see a 504 response from https://video.odl.mit.edu/api/v0/upload_videos/

**Comment by mbertrand** [comment]
I think the [celery task to stream videos to S3 and start transcoding jobs](https://github.com/mitodl/odl-video-service/blob/f4076d2025d5e1db9c0a91c09f141a845b564343/ui/api.py#L49-L52) is not running asynchronously:

```
        # Kick off chained async celery tasks to transfer file to S3, then start a transcode job
        task_result = chain(
            tasks.stream_to_s3.s(video.id), tasks.transcode_from_s3.si(video.id)
        )()
```

The `()` at the end should probably be replaced with `.apply_async()`

**Comment by pdpinch** [comment]
@collinpreston @mbertrand do you think we can close this?

**Comment by mbertrand** [comment]
I think so, it seems to be working well now
