### ISSUE TITLE
Make OmniPlayer javascript files available to the app

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#103]
Since OmniPlayer is not open source it can't be included in the odl-video-service repo.  Upload all its files (JS, CSS, images) to S3 and make them available via URL, for example:

```
https://s3.amazonaws.com/odl_mit_video/omniplayer/lib/omni-external-libs.js
```

Related to #93, which depends on this being in place.

**Comment by mbertrand** [comment]
Alternatively, if OmniPlayer can be transformed into a yarn-compatible JS package, put it in a private repo and use yarn and webpack to integrate it.

**Comment by mbertrand** [comment]
Current solution is to host the files on S3.  Waiting to here back from OmniLive whether or not they can package the files to be yarn-compatible.

**Comment by mbertrand** [comment]
OmniLive provided the new files in the standard format, not as a package.  So sticking with external url's for now

**Comment by pdpinch** [comment]
Isn't this done?

**Comment by mbertrand** [comment]
Yes as long as the current approach is acceptable (external script tags instead of webpack integration).

**Comment by pdpinch** [comment]
I'm afraid that's going to be up to the vendor.
