### ISSUE TITLE
multiple speed playback

### ISSUE THREAD

**Issue by emmello** [mitodl/odl-video-service#107]
A viewer will be able to have 1x, 2x, & 4x playback to match Omniview player capabilities.  Would also be desirable to have a .5 playback speed as well.

**Comment by pdpinch** [comment]
This is a built-in feature of video.js. We just need to specify the rates and it should work.

**Comment by mbertrand** [comment]
I was just testing it out and noticed that on Safari the audio doesn't play back at 4x speed.  However, it's unintelligible at that speed anyway, and USwitch player has the same issue on Safari.
