### ISSUE TITLE
USwitch player JS only works with specific MIT domains

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#108]
The USwitch player throws a JS error unless the domain from which it is loaded is localhost, mit.edu, or amps-web.amps.ms.mit.edu

The company which produces the player is working on modifications to fix this.

**Comment by mbertrand** [comment]
Received the new modifications but it will also require a slight change to the React component that renders it in OVS.

**Comment by mbertrand** [comment]
The change that needs to be made to the React component's `render` method:
```
        <div ref={ node => this.videoNode = node }  allowFullScreen id='omniPlayer'>
          <video id='video' playsinline webkit-playsinline></video>
        </div>
```

**Comment by mbertrand** [comment]
@pdpinch is it okay for me to work on this one this week since it's related to #109?

**Comment by pdpinch** [comment]
Yes
