### ISSUE TITLE
raise an error if USWITCH_URL is needed and not set

### ISSUE THREAD

**Issue by giocalitri** [mitodl/odl-video-service#112]

**Comment by pdpinch** [comment]
@shaidar @mbertrand is this working already?

**Comment by shaidar** [comment]
@pdpinch @mbertrand I don't believe so as I tried commenting it out in the uwsgi ini config and restart the process while tailing the logs and didn't see any errors about a missing key.

**Comment by pdpinch** [comment]
I think we can close this, since we removed the USWITCH player
