### ISSUE TITLE
Create custom 403, 404 and 500 pages

### ISSUE THREAD

**Issue by giocalitri** [mitodl/odl-video-service#116]

**Comment by gsidebo** [comment]
We might also want to have designs for a failed permissions page, which would be shown when a user tries to access a collection that they aren't allowed to view (for example)

**Comment by pdpinch** [comment]
@roberthouse54 Sorry if I've asked this before -- have you done designs for these?

**Comment by roberthouse54** [comment]
I posted some designs in product for feedback but didn't hear anything back. I will send them again.

**Comment by pdpinch** [comment]
Those are fine. Can you create a couple of templates similar to how they were implemented in [micromasters](https://github.com/mitodl/micromasters/tree/master/ui/templates) and then work with one of the engineers to wire them in?

**Comment by pdpinch** [comment]
@roberthouse54 can you take a look at creating templates similar to how they were implemented in [micromasters](https://github.com/mitodl/micromasters/tree/master/ui/templates) and then work with one of the engineers to wire them in?

**Comment by roberthouse54** [comment]
I think it might make more sense for an engineer to create an error page and then I could style it after.

**Comment by noisecapella** [comment]
I'll take a look
