### ISSUE TITLE
Tweak VideoJS CSS to prevent black bars

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#119]
Currently black bars may appear on the top/bottom or left/right of the video depending on the browser window width.  This can be fixed by tweaking the HTML and CSS:

in `video_detail.html`, add a wrapper around the `odl-video-player` div:
```
        <div class="wrapper">
         <div id="odl-video-player" class="video-odl-medium"></div>
        </div>
```

in `layout.scss`, remove videojs styles for everything but `video-odl-medium` and change that to:
```
.video-odl-medium{
    width:80%;
    max-width:1024px;
}
```

in `static/js/entry/video.js`,  set `fluid: true`

**Comment by pdpinch** [comment]
one idea: just set the "bars" to be white, same as the page background.

**Comment by mbertrand** [comment]
I tried the white/transparent background idea first but then things didn't look quite right with the menu bar at the bottom.

**Comment by pdpinch** [comment]
I believe this is fixed already.
