### ISSUE TITLE
USWITCH player not working in mobile browsers (Safari or Chrome)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#129]
Viewing http://video-ci.odl.mit.edu/videos/da8038ee8f6144dc9cd98526cb6640a1/ in Mobile Safari and Mobile Chrome, no video thumbnail displays and there's no video or audio. 

On the other hand, http://amps-web.amps.ms.mit.edu/courses/6/jun26/ appears to work as expected, which a touch-enabled USWITCH player.

**Comment by pdpinch** [comment]
@emmello is the USWITCH player supposed to work in mobile, with HLS video?

**Comment by emmello** [comment]
Yes, it should work on mobile devices.  I can't play it in Android, either.

**Comment by pdpinch** [comment]
we aren't using the USWITCH player any more.

**Comment by emmello** [comment]
USwitch is working on Production with my Android phone.

**Comment by emmello** [comment]
Oops, still call it that.  Ignore my response!
