### ISSUE TITLE
Camera boxes for USwitch don't work properly in Safari

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#130]
In the Safari browser, some or all the camera angle boxes just display black, depending on the video:

- For an original LectureCapture MP4 video (960x540), all 4 camera boxes work properly.
  - URL: https://d3tsb3m56iwvoq.cloudfront.net/transcoded/bigmitvide.mp4
- For the transcoded HLS version of the Lecture Capture video (960x540), all 4 are black:
  - URL: https://d3tsb3m56iwvoq.cloudfront.net/transcoded/63f6615177834cec82902bbf85bffc0a/video_1501854804980-4qywml.m3u8
- For a sample MP4 file downloaded from the web (320x176), 2 out of 4 are black:
  - URL: https://d3tsb3m56iwvoq.cloudfront.net/transcoded/jellies2.mp4
- For another MP4 (1280x720), all 4 camera boxes work properly:
  - URL: https://d3tsb3m56iwvoq.cloudfront.net/transcoded/wwtrailer.mp4
- For a sample HLS file from the web, all 4 are black:
  - URL: https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8

These were tested with the sample index.html page delivered by OmniLive and run locally.

**Comment by mbertrand** [comment]
PS There are no JS errors in the console, although "cooucou" is logged multiple times per second and probably should be removed from the omni-min.js script.

**Comment by pdpinch** [comment]
Still seeing this issue after the update to 1.032
