### ISSUE TITLE
Google analytics: Page view stats

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#139]

**Comment by mbertrand** [comment]
This is at least partially in the code already, but needs to be tested to see if it is actually working.

Also, @ferdi expressed interest in having some video-specific details (like % played, fullscreen toggled, playback started, etc) as provided by the [videojs-ga](mickey/videojs-ga) plugin.  However that plugin won't work for LectureCapture videos.

**Comment by mbertrand** [comment]
@pdpinch should I continue with this one for the next sprint?  The basics are done in terms of page analytics, next need to add analytics for videojs user actions like play, stop, etc. using a plugin.

**Comment by mbertrand** [comment]
Events made available in the videojs-ga plugin: 
```'loaded', 'percentsPlayed', 'start', 'end', 'seek', 'play', 'pause', 'resize', 'volumeChange', 'error', 'fullscreen'```

**Comment by mbertrand** [comment]
Video events sent back to the EdX server (but not GA) on a sample EdX video: `play, pause, menu shown, menu hidden, change speed, hide transcript, show transcript, seek video`.  Nothing but `pageview` seems to be sent back to Google Analytics.
