### ISSUE TITLE
Handle x509 certificates using environment variables

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#142]
In deployment environments like Heroku it's inconvenient to store certificates as a file on disk.  Yet the `requests` python package used in libraries such as mit-moira and pylmod expects certificates to be passed as filepaths; in particular, `requests.session.cert()`.

Our approach in other apps has been to put the certificate into a environment variable, write the variable to a file on startup, and then pass the file to a library like mit-moira.  In this case, it is recommended to write to a temporary file on startup, that will be overwritten each time the app is restarted.

**Comment by pdpinch** [comment]
Since there's a PR open, I'll move this into "In Progress"
