### ISSUE TITLE
Support for moira lists that contain e-mail addresses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#146]
Some moira lists contain e-mail addresses as well as kerberos user IDs. It would be nice for these to work the same with view and admin permissions as kerberos ids, but the mit-moira library doesn't currently return the e-mail addresses. 

See https://github.com/mitodl/mit-moira/issues/4

**Comment by mbertrand** [comment]
Emails are returned as well as kerberos IDs as part of #147;  checking both for permissions will need to be part of #52, #53
