### ISSUE TITLE
Send emails to all moira list admins and not only the collection owner

### ISSUE THREAD

**Issue by giocalitri** [mitodl/odl-video-service#154]
it will be enough to modify this function:
https://github.com/mitodl/odl-video-service/blob/master/mail/tasks.py#L17-L34

Since the moira lists that we use are also mailing lists, we can just append `@mit.edu` to the list name and send an e-mail to that address.

**Comment by pdpinch** [comment]
When building the mailing list, we should, if possible, union all the moira lists so as to avoid sending duplicate emails.

**Comment by mbertrand** [comment]
List membership returns kerberos id's for most MIT people and not email addresses.  The code can assume that the email is `<kerberos_id>@mit.edu`, but that may not always be correct. 
There is a Moira API call to get user information but it doesn't return email address.

**Comment by pdpinch** [comment]
When is <kerberos_id>@mit.edu not correct?

**Comment by mbertrand** [comment]
I think it was mentioned awhile back that some people might have subdomain emails like someone@sloan.mit.edu

**Comment by pdpinch** [comment]
I updated the description based on our Slack discussion.

**Comment by pdpinch** [comment]
AFAIK, this is working in production.
