### ISSUE TITLE
Celery exceptions not getting logged properly

### ISSUE THREAD

**Issue by noisecapella** [mitodl/odl-video-service#155]

**Comment by pdpinch** [comment]
@noisecapella is this still an issue? 

Are they getting raised to Sentry properly?

**Comment by pdpinch** [comment]
@noisecapella is this still an issue? 

Are they getting raised to Sentry properly?

**Comment by noisecapella** [comment]
I'm not sure, I haven't had a chance to do investigation on this

**Comment by mbertrand** [comment]
Some recent observations on docker:
- Exceptions that occur outside of a try-catch block seem to just disappear (no logs, and video  statuses not updated)
- Exceptions that do occur inside a try-catch block trigger a mail alert but don't show up in the logs without an explicit `log.exception()`
