### ISSUE TITLE
Create a Mailgun domain record for OVS

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#168]
Mailgun is currently using the micromaster domain to send emails (https://api.mailgun.net/v3/micromasters.odl.mit.edu).  The OVS domain has to be added to our Mailgun account to avoid having a micromasters email show up in the details of the message sender.

>To be able to use Mailgun in production a custom domain(s) has to be created and verified with Mailgun.
>Verifying your domain is easy. Start by adding a domain or subdomain you own in the Domains tab of the Mailgun control panel. Next add two TXT DNS records found in the Domain Verification & DNS section on the domain information page of the Mailgun control panel at your DNS provider:

http://mailgun-documentation.readthedocs.io/en/latest/user_manual.html#sending-via-api

**Comment by pdpinch** [comment]
This is done right?
