### ISSUE TITLE
Add more unit tests for existing functionality

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#17]
There should be more unit tests for existing functionality & models.

**Comment by pdpinch** [comment]
This would need to be more specific before we can start working on it.

Can I suggest that we add unit tests as we go, when we add new functionality, by backfilling them to areas that are being touched?

**Comment by pdpinch** [comment]
I'm going to close this because we've added a lot of tests and we're adding more as we add features and refactor code. 

If there are specific tests that you think are still lacking, please open specific issue(s).
