### ISSUE TITLE
Increase size of Video Thumbnails

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/odl-video-service#173]
The video thumbnails are created in transcoding, and the size is based on AWS presets. The current size of thumbnails is too small for the design, so we want to increase the size.

Currently they are sized to a max-height of 108px OR a max-width of 192px, whichever comes first. 

We want to increase these to be max-height of 338px or max-width of 600px.

**Comment by mbertrand** [comment]
- Update `config/et_presets.json` with new thumbnail sizes
- Run `python manage.py createpresets` to generate new presets
- Set `ET_PRESET_IDS` to the list of new presets
