### ISSUE TITLE
Video URL is embed URL, not the link to the video page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/odl-video-service#179]
It should be the link to the video detail page

**Comment by pdpinch** [comment]
We have some users relying on this behavior at the moment, because they don't want students to see all the videos in the collection until they're ready to release them.

**Comment by pdpinch** [comment]
@emmello this is an old issue that George raised. Do you think this needs to be changed?

**Comment by emmello** [comment]
I would leave it as is, since that's what people are currently using.
