### ISSUE TITLE
Update the upload UI

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#183]
After selecting a file for upload return the users to the collection detail page. Display the current video status instead of the thumbnail (which won't have been created yet). 

There's no need for a progress bar, since it's not useful information for the user. 

If the transcode fails for some reason, the status should also be displayed instead of the thumbnail.

**Comment by mbertrand** [comment]
The upload progress bar for each selected Dropbox file needs to be shown in a new card on the collection detail page, with no form fields to update title or description, as shown here:
https://projects.invisionapp.com/boards/863980TEFVYP7#/5469149/167848254

**Comment by pdpinch** [comment]
Is this still an issue?

I'm not really interested in the progress bar, but I don't want things to look broken. Can we just update the CSS?

**Comment by mbertrand** [comment]
The overlapping fields described in the initial comment are no longer an issue (they've been removed).  But the upload form and progress indicators are still on a separate page with no header or footer.

**Comment by pdpinch** [comment]
closed in favor of #226
