### ISSUE TITLE
Style Collection List Page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#185]
This page: https://video.odl.mit.edu/collections/ needs some design. 

Should be as simple as possible, possibly a simple implementation of https://material-components-web.appspot.com/list.html

- [ ] "Create New Collection" should be at the top of the list

**Comment by gsidebo** [comment]
@roberthouse54 Guessing this issue doesn't cover the implementation of this UI where a user doesn't have any collections yet (https://projects.invisionapp.com/boards/BH3980T9CM2AU/)? If not, we can create a separate issue. Also, I'm guessing the 'Create Collection' link will need to match the button in that same design. In short, this is going to involve some non-trivial React code changes, so if you want to hand this off, let me know

**Comment by roberthouse54** [comment]
![collections1](https://user-images.githubusercontent.com/20047260/30346523-05ad91c2-97d7-11e7-9a27-872c291efa6f.png)

![collections2](https://user-images.githubusercontent.com/20047260/30346527-09301b1c-97d7-11e7-8b15-1916c02c4962.png)
