### ISSUE TITLE
Footer cleanup

### ISSUE THREAD

**Issue by Ferdi** [mitodl/odl-video-service#192]
![footer](https://user-images.githubusercontent.com/125561/30115817-cec1569a-92e9-11e7-9725-1571b8d4763c.png)

- Remove "edx" link
- Remove "Give to MIT" link
- Move copyright text on the right
- There should be more space between header and footer even when tehre is no videos in the collection, see below

![footer2](https://user-images.githubusercontent.com/125561/30116568-e66b0a32-92eb-11e7-82f8-16f744b48d05.png)

**Comment by roberthouse54** [comment]
This is all set. The only thing is that I have not moved the copyright to the right, as I think the design works better to keep all the text aligned left.
