### ISSUE TITLE
Ability to add hyperlinks in collection descriptions

### ISSUE THREAD

**Issue by emmello** [mitodl/odl-video-service#196]
As an admin user I would like to add in a Qualtrics survey link to the collection description to encourage students to fill out the survey on what they think about the lecture capture.  Currently, pasting a link in the descriptions just displays it as text and not a clickable link.

**Comment by pdpinch** [comment]
I don't think this is going to work as well as the faculty contact student directly. 

If we do this, it's going to open a can of worms about HTML support.
