### ISSUE TITLE
Video fails transcoding yet shows up in collection

### ISSUE THREAD

**Issue by shaidar** [mitodl/odl-video-service#200]
When a video fails to transcode it appears that it still makes it to the collection. I'm assuming that ideally if it fails transcoding, it shouldn't show up in the collection.
![screen shot 2017-09-08 at 7 53 31 am](https://user-images.githubusercontent.com/1447295/30210490-da394352-946a-11e7-8a30-0e3cb7186d33.png)

![screen shot 2017-09-08 at 7 57 55 am](https://user-images.githubusercontent.com/1447295/30210685-7f0bbf68-946b-11e7-83af-276bdf5d9060.png)

**Comment by pdpinch** [comment]
We can live with this.
