### ISSUE TITLE
Loading a collection detail URL by forbidden user causes endless request loop

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#203]
If users attempt to load a URL for a collection they don't have view permission for, a blank page will result. However, the network console indicates that the URL is being repeatedly & rapidly requested via a React component in an endless loop (always resulting in a 403 response).

**Comment by mbertrand** [comment]
@pdpinch, I figured out a quick fix for this, just putting one line instead an `if` condition. Should I go ahead and make a PR?

```javascript
  componentDidUpdate() {
    if (!this.props.collectionError) {
      this.updateRequirements();
    }
  }
```

**Comment by aliceriot** [comment]
that looks like the right idea

**Comment by aliceriot** [comment]
although you may also want to check that the data is not already there - I'm not super familiar with the code though
