### ISSUE TITLE
Enable scrollbars for dialogs

### ISSUE THREAD

**Issue by gsidebo** [mitodl/odl-video-service#205]
Our dialog components do not have internal content-level scrollbars, and they don't create window-level scrollbars when the dialog is too tall for the browser window. This can potentially cause some significant usability problems, especially for the collection create/edit form on the collection detail page which occupies a lot of vertical space. We should either make the dialog window shrink-able and enable internal content-level scrollbars, or figure out how to get window-level scrollbars to show up.

**Comment by pdpinch** [comment]
Is the dialog component something we wrote, or is it from a library?

**Comment by gsidebo** [comment]
Mostly from a library, but the actual react code for all of our MDC components was basically copied/pasted into our codebase from the samples on their site, and from there we've made some small tweaks to them.
