### ISSUE TITLE
Enable collection creation via dialog form

### ISSUE THREAD

**Issue by gsidebo** [mitodl/odl-video-service#206]
#190 added a dialog form to edit a collection. This same form can/should be leveraged to create a new collection. 

For ease of testing, it probably makes sense to add the 'Create Collection' link in the sandwich menu as shown [here](https://projects.invisionapp.com/boards/Q33980TUMV29A/) and wire it up to open that form.

**Comment by pdpinch** [comment]
closed in favor of #227
