### ISSUE TITLE
Redirect to login page after logging out

### ISSUE THREAD

**Issue by gsidebo** [mitodl/odl-video-service#208]
Logging out directs the user to `/logout` where they are shown a simple message. The user needs to manually enter a URL to log back in. We should redirect the user directly to the login page after they log out.

**Comment by pdpinch** [comment]
but there is no login page, because we're using Touchstone SSO.

I suppose we could provide a link that says "login" but it could just link to the home page.

**Comment by gsidebo** [comment]
We do currently have a login page in the app (`/login`), and even when Touchstone integration is finished (maybe it is already?), I really think we should keep it around for non-production environments. Touchstone as the only login method would make it very difficult to test the app locally, I think
