### ISSUE TITLE
Add form validation to video edit form to prevent blank titles

### ISSUE THREAD

**Issue by gsidebo** [mitodl/odl-video-service#209]
We currently have 2 forms that take user input for some basic CRUD operations: collection edit and video edit. Both of these forms need some basic validation and UI tweaks to show error messages.

**Comment by Ferdi** [comment]
What currently happens if something does not validate ?

**Comment by gsidebo** [comment]
Right now I don't think there's a way to send a request that causes an actual server-side error, but we should at least validate on the front end to prevent users from setting the title of a collection or video to a blank string. Right now that's an acceptable value on the server side

**Comment by roberthouse54** [comment]
We need to add a design for validation errors on form submission. Styling as follows:

    background: #ffe8ec;
    color: #f15a74;
    padding: 8px;
    font-size: 15px;

See mock below:

![30343168-6b592aca-97ca-11e7-9bf0-b3950a9a80c6](https://user-images.githubusercontent.com/20047260/30491120-3665b54e-9a0a-11e7-9d3d-5c446969d5da.png)

**Comment by Ferdi** [comment]
@gsidebo  looking at  this demo , https://material-components-web.appspot.com/textfield.html   textfield support validation. What are we trying to do here ?

**Comment by gsidebo** [comment]
@Ferdi That will work for us. We simply haven't done the work yet to detect errors in text inputs, return appropriate error messages, and supply those error messages to the MDC components

**Comment by pdpinch** [comment]
@mbertrand I know we have validation now on moira lists. Is there more work that should be done here?

**Comment by mbertrand** [comment]
@pdpinch the video edit form still needs validation to prevent blank titles.
