### ISSUE TITLE
Bug: After opening a modal, scrolling no longer works

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/odl-video-service#213]
To reproduce:

Go to the Video Details page and scroll down. 
Click either "Edit" or "Share".
Close the modal, either by clicking close or cancel, or by clicking outside the modal.
Try to scroll up, and scrolling does not work.

I found this bug on Mac/Chrome.

**Comment by mbertrand** [comment]
This has something to do with the `hideDialog` function called on clicking a Dialog's button, which in turn calls [`updateDialogVisibility`](https://github.com/mitodl/odl-video-service/blob/12ed34e1dbc5a4c3bcd7b8c5614dec7c4915fa80/static/js/lib/dialog.js#L13-L19).  If the hideDialog function is not called, the dialog will still close, after which scrolling works properly on the page.  However, clicking the button to show the dialog again no longer has any effect.

My guess is that changing the state in this function somehow interferes with MDC's call to close the dialog, and so the dialog's disabling of scrolling isn't cleared.  But haven't had any luck so far in figuring out how to avoid this problem and still be able to re-open the dialogs a second time.  Any ideas @gsidebo ?

**Comment by gsidebo** [comment]
I'm guessing we'll have to do something similar to `static/js/components/material/Toolbar.js`, where we manually destroy an MDC-created object, or `static/js/components/material/Drawer.js`, where we add a listener to a DOM node directly

**Comment by mbertrand** [comment]
Thanks for the tip!
