### ISSUE TITLE
Create VideoTranscript model

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#216]
- [ ] Create a `VideoTranscript` model, similar to `VideoThumbnail` and `VideoFile`.
- [ ] Fields: `video_id`, `s3_key`, `language`
- [ ] The relation between Video and VideoTranscript will be one-to-many (just in case multiple language support is added in the future).
- [ ] Assumption is that the transcript files will be stored in S3 like the thumbnails and videofiles, and will have their own bucket.

**Comment by mbertrand** [comment]
@pdpinch @shaidar @blarghmatey Do you have any preference on whether transcripts are saved to their own S3 bucket or to an existing bucket?  Currently there are buckets for uploads, thumbnails, and transcoded videos.

**Comment by mbertrand** [comment]
@pdpinch @shaidar @blarghmatey Never mind, should have their own bucket. Can you create buckets for ci, rc, production using same name pattern, but with `transcripts` in the name.  Also set them up for use with Cloudfront.

**Comment by shaidar** [comment]
@mbertrand Yeah I can work on that.

**Comment by mbertrand** [comment]
@pdpinch Since these will be displayed to the user as 'Subtitles', okay with you if I use `VideoSubtitle` as the model name?

**Comment by pdpinch** [comment]
Yes, please!
