### ISSUE TITLE
Allow upload/delete of Video Transcript 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#220]
The edit widget for videos should be modified to allow the user to upload captions or delete existing captions.

**Comment by mbertrand** [comment]
@pdpinch should caption uploads & deletions occur as soon as the appropriate button/link is clicked, or only when the 'SAVE CHANGES' button is clicked?

![screen shot 2017-09-14 at 8 43 07 am](https://user-images.githubusercontent.com/187676/30430368-032d3bc0-9929-11e7-8fc7-3d3705f16bda.png)

**Comment by pdpinch** [comment]
If there's a save button, it seems like it should happen when save gets clicked. But I don't have a strong feeling about it. What's easier?

FYI @roberthouse54

**Comment by mbertrand** [comment]
I believe I'll have to make separate API calls for each (save title/description, delete transcript, upload transcript) but it should be possible to do them all at once when the 'Save Changes' button is clicked.  In that case, @roberthouse54 what do you think of making the delete link a checkbox (`[] Delete`)?

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/30490212-50c5e1fa-9a07-11e7-9543-582fae37a1c6.png)
![image](https://user-images.githubusercontent.com/20047260/30490229-5b1f76a2-9a07-11e7-95c6-d5f3efa34477.png)

**Comment by roberthouse54** [comment]
So the design on this has changed a bit, just FYI.

**Comment by roberthouse54** [comment]
We are going to use the term "Subtitles / CC"... which is what Youtube does.

**Comment by mbertrand** [comment]
@pdpinch is it still okay to skip the language selection for this sprint, just upload a file and assume it's English?

**Comment by pdpinch** [comment]
Yes, let's assume English (captions) for all uploads and playback. 

If we do multiple subtitle languages it would be a future enhancement.
