### ISSUE TITLE
add transcript download link to video detail page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#221]
Some users will want to download a copy of the transcript. And currently, the USWITC player doesn't support playback of timed transcripts.

To address both of these cases, we can present a link to download transcript(s) on the Video Detail page.

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/30490564-4d357978-9a08-11e7-9b88-c4af71623994.png)

After the user clicks the download link, the video should start downloading immediately. The icon should have alt="Download this Video".
