### ISSUE TITLE
retry transcode on failures

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#23]
Part of #19 

It's my understanding that transcode failures are not uncommon. Since the transcode process can be slow, we would like them to be automatically retried, instead of relying on the user or an admin to notice that the transcode has failed and request a retry.

**Comment by mbertrand** [comment]
If I understand the following correctly, elastic transcoder should by default retry up to 5 times before marking a job as a failure:

https://aws.amazon.com/blogs/developer/throttled-retries-now-enabled-by-default/
http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/error-handling.html#api-retries
https://github.com/boto/boto3/issues/770
https://github.com/boto/botocore/blob/develop/botocore/data/_retry.json#L75-L94

**Comment by pdpinch** [comment]
5 tries sounds good enough to me. What are our options for notifications after 5 failures (i.e issue #24)?

**Comment by mbertrand** [comment]
Sentry notifications for devops?
For users, list the status if the transcoding job on the video detail page. Maybe show details as well on why it failed?
