### ISSUE TITLE
Future enhancement - ability to trim video or select a specific start time

### ISSUE THREAD

**Issue by emmello** [mitodl/odl-video-service#232]
Recordings for lecture capture start 3 - 5 minutes prior to the start of the lecture so as to not lose any of the lecture if the faculty starts early.  There's then some downtime before the class starts and past requests have asked for files to be trimmed to the actual class start time.  

If there was a way to use a virtual time that could be inputted for playback, that would be fine or a way for them to do a trim edit and convert the file with the same link, that would be a useful option in the future.  And example would be this video which actually starts the talk at 4:05:

https://video.odl.mit.edu/videos/2e9550fec00b4a3294f68670c7fd7862/

**Comment by Ferdi** [comment]
We should probably support "start time" in url  and embed code, similar to what youtube does.  So our url could look like 

https://video.odl.mit.edu/videos/2e9550fec00b4a3294f68670c7fd7862/#start=134

**Comment by pdpinch** [comment]
Closing this in favor of #279
