### ISSUE TITLE
Validate moira-list input

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#233]
When entering moira-lists for collections, validate that the lists actually exist.

**Comment by Ferdi** [comment]
@mbertrand Does the api support this ?

**Comment by mbertrand** [comment]
Yes:
```python
mc = get_moira_client()
mc.list_exists('my-custom-moira-list')
```

**Comment by pdpinch** [comment]
Do you know if there's a way to validate if the list is a mailing list?

**Comment by mbertrand** [comment]
There is a boolean `mailList` attribute for each list that I think reflects this:
```python
mc = get_moira_client()
attributes = mc.client.service.getListAttributes('odl-engineering', mc.proxy_id)
attributes[0]['mailList']
```

**Comment by mbertrand** [comment]
Should we validate both that the list exists and is also a mailing list?

**Comment by pdpinch** [comment]
I think so. 

Is that easy to do?

**Comment by mbertrand** [comment]
Yes

**Comment by pdpinch** [comment]
moving this to "In Progress"
