### ISSUE TITLE
Formatting issues in Safari

### ISSUE THREAD

**Issue by shaidar** [mitodl/odl-video-service#244]
`Edit Video Details` and `Share this Video` are weirdly placed on the video thumbnails in Safari. Also doesn't look like the video title is appearing.

![screen shot 2017-09-15 at 5 10 56 pm](https://user-images.githubusercontent.com/1447295/30503877-f03f34a2-9a39-11e7-81f0-b820509f22e7.png)

**Comment by roberthouse54** [comment]
I looked at this and can't figure out what is happening, so I am unassigning myself. Flex is still only partly supported by browsers, and I think this may be an issue that requires a workaround for safari. @aliceriot would you take a look at this? You know more about flexbox than I do.

**Comment by aliceriot** [comment]
I'm not sure what's up - I don't have safari on my machine so I am probably not the best person to try to figure this out.
