### ISSUE TITLE
allow admins to masquerade as another user

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#245]
As an admin, when I'm working on a support ticket, I'd like to be able to view the site "as" another user. This would also remove the need for maintaining multiple accounts with different permissions for testing.

**Comment by pdpinch** [comment]
There is a list of django packages that do this at https://djangopackages.org/grids/g/user-switching/

**Comment by adorsk** [comment]
After some cursory research, I'm going forward with https://github.com/arteria/django-hijack . It does what we want, and has good docs and test coverage.
