### ISSUE TITLE
Add OVS to BI

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#257]
for future analysis of OVS, it would be useful to have its postrgres database and its Google Analytics data available in BI.

**Comment by pdpinch** [comment]
FYI @maxliu

**Comment by blarghmatey** [comment]
The GA data is now available in BI. The database data needs to wait until we have it running in RDS as right now everything is on a single EC2 node.

**Comment by pdpinch** [comment]
@mitodl/devops can this be closed?
