### ISSUE TITLE
allow collection admins to download source video

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#261]
As a collection admin, I'd like to be able to download my video from OVS, for example to submit it to a transcription service or to edit it.

**Comment by roberthouse54** [comment]
Basically we add a download link to the Video details page, and the video card. Once clicked the video begins downloading immediately.

![30493446-149734ee-9a12-11e7-8552-c980902eeaa4](https://user-images.githubusercontent.com/20047260/30703571-12b4c4ce-9ebe-11e7-82fc-703c98c45ffa.png)

![image](https://user-images.githubusercontent.com/20047260/30703895-fd73a3ae-9ebe-11e7-90f4-15f9a76dabcf.png)

**Comment by roberthouse54** [comment]
Clicking the menu icon in the video card reveals the overflow menu with the download option. On the Video details page, there will be a download button. Once clicked the video begins downloading immediately. 

![image](https://user-images.githubusercontent.com/20047260/31133190-c598c988-a82c-11e7-9a4a-1fea166ca57f.png)

![image](https://user-images.githubusercontent.com/20047260/31133444-85c3a30e-a82d-11e7-9551-a65ddbbc2fad.png)

**Comment by mbertrand** [comment]
@pdpinch Is it okay to download via django proxy?  This would solve a few issues:
- Hides the actual Cloudfront download URL, which requires no authentication.  URL would be http://video.odl.mit.edu/download_video/<video_key> and require admin permission.
- Customization of content-type in the download header, to prevent the video file from automatically loading & playing in the browser page.
- Customization of the download filename.

However, it does require more bandwidth - the download streams from S3 to the web server and on to client.

**Comment by pdpinch** [comment]
I think there's a detail missing from the description: we want the download to go to dropbox.

**Comment by mbertrand** [comment]
That might be confusing to users, I think most people would assume 'download' means 'transfer the file to my computer', not 'transfer the video to dropbox'.

**Comment by mbertrand** [comment]
If users want to edit the video or send it to a transcription service, they'll need to download it to their computer anyway, unless they plan to use only online editing/transcription services that integrate with Dropbox.
