### ISSUE TITLE
Admin page for EncodeJob hangs indefinitely on RC, Production, but not CI (yet)

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#269]
https://video-rc.odl.mit.edu/admin/dj_elastictranscoder/encodejob/
https://video.odl.mit.edu/admin/dj_elastictranscoder/encodejob/

The above URL's hang indefinitely.  RC and Production both have ~100+ videos at the moment (so same number of EncodeJobs) but CI has half that.  However my docker instance also has >100 videos and doesn't have this problem.  Maybe it's a memory issue on the instances.

**Comment by shaidar** [comment]
This is related to this reported [issue](https://github.com/encode/django-rest-framework/issues/3982). I changed log level to INFO in video (seems to be working now) and left it at DEBUG for now on rc as the shib work continues.

**Comment by mbertrand** [comment]
The page still isn't loading for me at https://video.odl.mit.edu/admin/dj_elastictranscoder/encodejob/

**Comment by pdpinch** [comment]
@mbertrand has this issue been fixed?

**Comment by mbertrand** [comment]
Yes
