### ISSUE TITLE
Add toast messages when saving changes, uploading etc. 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#272]
As a collection admin, when I change settings on a video or a collection, or when I upload a transcript file, it's not obvious that my changes have been submitted and accepted. 

We should display a brief toast message in these cases, confirming that changes have been saved for the user.

**Comment by roberthouse54** [comment]
Here is the UI:

Toasts are displayed at the top of the page, centered. They show for a certain amount of time, then they fade away. Success toast messages include a checkbox icon as shown.

![image](https://user-images.githubusercontent.com/20047260/30872288-8a6d3580-a2b7-11e7-9b6b-05623be42754.png)

We should show a toast after every form submission or user-initiated change on a page.
Editing a video: "Changes saved"
Deleting a Video: "Video deleted"
Creating a Collection: "Collection Created"
Editing a channel: "Changes saved"
On subtitle upload: "Subtitles uploaded"
Deleting subtitle file: "Subtitle file deleted"
Downloading subtitles: [do not show a toast in this case]
Uploading Video: [do not show a toast in this case]

**Comment by pdpinch** [comment]
@roberthouse54 @mbertrand do you know if this was implemented?

**Comment by adorsk** [comment]
Closed by above PRs.
