### ISSUE TITLE
Display video counts in the drawer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#273]
As a user, I find it helpful to see the count of videos on the collection list (`/collections`) and I'd like to see the count in the drawer as well.

**Comment by roberthouse54** [comment]
Let's just add a simple number in parentheses next to the Collection name. See below:

![pasted image at 2017_09_26 12_17 pm](https://user-images.githubusercontent.com/20047260/30875364-4b72af90-a2c1-11e7-9c11-360b5a4cf452.png)
