### ISSUE TITLE
add Help page and links

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#274]
As a collection admin, I'd like to be able to access some basic instructions on how to use the site. 

We need a "Help" page which is prominently linked on the collection page. 

The Help page can be organized as FAQs, with linkable anchors so we can use specific URLs when answering support questions.

**Comment by roberthouse54** [comment]
The content for this needs to be written.

**Comment by roberthouse54** [comment]
Design can be pretty simple. This one is basically the same as the Micromasters FAQ.

![image](https://user-images.githubusercontent.com/20047260/31517885-4cb76092-af6b-11e7-8004-cfabe8c1fdba.png)

**Comment by roberthouse54** [comment]
We will show a card on the collections page that shows a "Learn More" link. Clicking this goes to the FAQ page. We will also add a link in the sidenav called "Help" which will also link to the FAQ page.

The copy for this is here: https://docs.google.com/spreadsheets/d/1Eq0nYsfpQ7XTEi1_2tT8fuf8gw6ysfp3i5PAKntr4BQ/edit?usp=sharing

![1](https://user-images.githubusercontent.com/20047260/32007948-f525c388-b978-11e7-926a-4ce20a7f9cc0.png)

![2](https://user-images.githubusercontent.com/20047260/32007953-f98779e4-b978-11e7-8e74-9e2e607354e1.png)

![3](https://user-images.githubusercontent.com/20047260/32007956-fc89bc74-b978-11e7-96e3-95fe5c8bf7bc.png)

**Comment by aliceriot** [comment]
did we have an idea yet of what the URL for the help page should be?

**Comment by pdpinch** [comment]
Good question, which we haven't discussed. I would go with `/help`
