### ISSUE TITLE
Remove JS code for video card actions in collection detail

### ISSUE THREAD

**Issue by gsidebo** [mitodl/odl-video-service#277]
@roberthouse54 is removing the actions in the collection detail video cards as part of #276. To accomplish the styling changes we're simply hiding the actions in CSS in that PR, but we'll need to go through the React code to remove those elements in earnest and clean up any now-deprecated functionality/tests.

**Comment by roberthouse54** [comment]
This is on hold. We are discussing not doing this, and instead implementing an overflow menu in the cards.

**Comment by pdpinch** [comment]
@roberthouse54 is this still relevant?

**Comment by roberthouse54** [comment]
I am not sure. I looked at the code and I do not see the old action icons anymore.

**Comment by pdpinch** [comment]
@gsidebo do you know if this is still relevant?

**Comment by gsidebo** [comment]
Closing this. The video card actions are no longer hidden via `display: none`
