### ISSUE TITLE
Lecture Capture: handle filenames with start times

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#282]
Sometimes, when there's an issue with the 1Beyond encoder, the filenames of lecture capture files will include the start time. Instead of creating a new collection for these, we should just ignore the time in the file name. 

For example:

```
MIT-8.05-2017-Fall-lec-mit-0000-2017sep25-1318-L01.mp4
MIT-8.05-2017-Fall-lec-mit-0000-2017sep25-1232-L01.mp4
```

**Comment by adorsk** [comment]
Collection names derived from lecture capture filenames currently use just the prefix (e.g. `MIT-8.05-2017-Fall`), the date (e.g. `2017sep25`), and the session (e.g. `L01`), per [cloudsync/api.py#L283](https://github.com/mitodl/odl-video-service/blob/109d82b708380dd9fa65c3e695b194caea469c4a/cloudsync/api.py#L283) . Closing this issue.
