### ISSUE TITLE
multiangle playback in VideoJS

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#283]

**Comment by mbertrand** [comment]
@pdpinch @ferdi Here's a screenshot of what it looks like now.  Any preference on where the boxes go (top, side, bottom)?  One remaining issue is that the boxes are not visible in fullscreen mode (they are visible with USwitch player).

![screen shot 2017-09-29 at 1 37 19 pm](https://user-images.githubusercontent.com/187676/31028408-d2fd349c-a51b-11e7-8174-c5580a204b06.png)

**Comment by roberthouse54** [comment]
I think either on the right or the bottom would be preferable. Probably on the right would be my preference.

**Comment by pdpinch** [comment]
Looks like a great start. 

I don't have a strong feeling about location, but I think I'd prefer the right or the bottom. 

Where are you keeping the code? Have you looked into making it a plugin?

**Comment by mbertrand** [comment]
@pdpinch the code is in the odl-video-service repo.  At this point I don't think it's a good candidate for a plugin, it's basically using HTML canvas elements on the page to redraw the 4 corners of the video in separate div's.

**Comment by mbertrand** [comment]
@pdpinch @roberthouse54 @Ferdi 

Updated screenshots, camera boxes are now visible in fullscreen.

![screen shot 2017-10-02 at 2 38 09 pm](https://user-images.githubusercontent.com/187676/31093364-88670f32-a77f-11e7-82ad-5cbc86dced9d.png)

![screen shot 2017-10-02 at 2 38 53 pm](https://user-images.githubusercontent.com/187676/31093371-8c2ba600-a77f-11e7-9851-73be4bbefad8.png)

**Comment by emmello** [comment]
These look good - let me know if there's a place to test this and I'd be happy to check on difference devices.
