### ISSUE TITLE
Transcode videos after uploading

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#3]
- Use AWS Elastic Transcoder.
- Transcode to multiple bitrates/resolutions? Robert mentioned transcoding at 4 bit-rates for current TechTV

**Comment by Ferdi** [comment]
@mbertrand can we copy the settings from the current techtv elastic transcoder ?

**Comment by mbertrand** [comment]
@Ferdi  Reviewing my notes, looks like Robert told me the multiple bit-rates were for lecture capture (1.0,1.8,2,2.8 mb/sec), I will ask if he has the full transcoding configuration available for TechTV.  When I tried out the current TechTV site I didn't see links to alternate video resolutions/bit-rates after the transcoding completed for my video, so there may be just one.

**Comment by mbertrand** [comment]
Robert: 

> "TechTV processes the original file into 5 different “flavors.”:
> Small.mp4
> Medium.mp4
> Basic.mp4
> Large.mp4
> HD.mp4
>  
> Small.mp4 serves clients with approx. 100kbps connectivity (low-end ISDN). The other extreme, HD.mp4, is approx. 2500kbps and is suitable for most US-based broadband access. The three in-between encodes are available as detected bandwidth allows (our heavily-customised FlowPlayer uses their standard bandwidth detection plug-in.)"

**Comment by mbertrand** [comment]
@pdpinch Robert mentioned that there is a private "StarCluster/Transcluster" repo that has the AWS Elastic Transcode profiles for each of the above video sizes, could you give me access to those?

**Comment by pdpinch** [comment]
I'm hoping he means: https://github.com/TechTV/transcluster

Let me know if that doesn't answer your questions.

**Comment by mbertrand** [comment]
Thanks, that's it: https://github.com/TechTV/transcluster/blob/develop/configs/et/transcluster-presets.json
