### ISSUE TITLE
Video embed not working due to CORS

### ISSUE THREAD

**Issue by noisecapella** [mitodl/odl-video-service#302]
I copied and pasted an iframe embed link in the homepage of my local micromasters instance and got this error:

![screenshot from 2017-10-06 11-24-08](https://user-images.githubusercontent.com/863262/31285348-0b5d15ba-aa89-11e7-99b8-5e272ac99048.png)

**Comment by pdpinch** [comment]
@mbertrand is this still an issue?

**Comment by mbertrand** [comment]
Yes

**Comment by pdpinch** [comment]
Is this an issue for @mitodl/devops -- perhaps a change to the nginx config to include a modified CORS header for the embed route?

We have a user interested in testing embeds, so we might need to fix this quickly now.

**Comment by mbertrand** [comment]
No, @blarghmatey mentioned that the appropriate headers can probably be inserted via code on the Django end.

**Comment by mbertrand** [comment]
This might be solved by just adding this decorator to the embed view:
```python
@method_decorator(xframe_options_exempt, name='dispatch')
class VideoEmbed(TemplateView):
```
