### ISSUE TITLE
Google Analytics: capture video events

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#304]
As a collection admin, I would like to know how many viewers have viewed my video and how they interacted with it. 

There appears to be a number of Google Analytics plugins for VideoJS. We should choose one that supports a reasonably similar set of events to what edX collects, in the interests of supporting similar analysis tools. It would also be useful to find one that is extensible so we can track multiangle playback events.

**Comment by mbertrand** [comment]
Events available in videojs: `'loaded', 'percentsPlayed', 'seeked', 'play', 'pause', 'ended', 'resize', 'volumeChange', 'error', 'fullscreen'`.  

Video events sent back to the EdX server (but not GA) on a sample EdX video: `play, pause, menu shown, menu hidden, change speed, hide transcript, show transcript, seek video`. Nothing but pageview seems to be sent back to Google Analytics.

@pdpinch @ferdi does this seem like a reasonable list of events to collect stats on: `play, pause, ended, seeked, percentsPlayed (10% increments?), fullscreen`?  I could look into monitoring subtitle activation too.

**Comment by Ferdi** [comment]
@mbertrand sounds good

**Comment by mbertrand** [comment]
Here's some initial results.  For each video page, a list of events:

<img width="438" alt="screen shot 2017-10-11 at 3 55 14 pm" src="https://user-images.githubusercontent.com/187676/31463089-cb71be20-ae9c-11e7-9e97-e7fc2d3d3c82.png">

For each event, there will be a list of values, which for most will be the time in the video at which they occurred, for example 'pause':

<img width="440" alt="screen shot 2017-10-11 at 3 56 05 pm" src="https://user-images.githubusercontent.com/187676/31463296-e35a49e4-ae9c-11e7-9d1d-6a188623c785.png">
