### ISSUE TITLE
Radio buttons lose selection in edit collection dialog

### ISSUE THREAD

**Issue by noisecapella** [mitodl/odl-video-service#319]
To reproduce:
- go to a collection you are admin of
- Bring up the edit collection dialog. You should see that the 'Who can view' and 'Who can upload' areas have radio buttons where one of the two items is selected.
-  Type something in one of the moira list textboxes. The radio buttons lose their selection

**Comment by emmello** [comment]
I had no problem in Chrome just now.

**Comment by noisecapella** [comment]
@emmello Do you have some free time today to try to reproduce this?

**Comment by emmello** [comment]
Sure, I'm available any time.

**Comment by mbertrand** [comment]
This seems to have something to do with the CollectionFormDialog being loaded twice, removing [this section of code](https://github.com/mitodl/odl-video-service/blob/master/static/js/containers/WithDrawer.js#L47-L49) from `WithDrawer.js` appears to fix the issue:
```
  withDialogs([
    {name: DIALOGS.COLLECTION_FORM, component: CollectionFormDialog},
  ])
```
With or without the above code though, the `Create a Collection` button on the drawer only works on collection pages, not video detail pages (I'll open another issue for that).

**Comment by adorsk** [comment]
this is no longer an issue, closing.
