### ISSUE TITLE
502 error at https://video.odl.mit.edu/

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#325]
It appears that if you have a stale Touchstone session and access https://video.odl.mit.edu/ you will get a 502 Bad Gateway error. Once in this state, you can get out of it by entering the URL https://video.odl.mit.edu/collections

This is not reproducible in a Private Window.

**Comment by pdpinch** [comment]
Sar and I found a UWSGI error occurs when I load the page, and nginx complains about request size. Removing my odl.mit.edu cookies (in particularly the JWT cookie for open-discussions) seems to clear the issue.

**Comment by shaidar** [comment]
Added `buffer-size=32768` to the uwsgi config in `/etc/uwsgi-emperor/vassals/odl-video.ini` on RC and need to test.

**Comment by noisecapella** [comment]
There are some nginx settings we needed to tweak when dealing with a similar issue: https://github.com/mitodl/micromasters/issues/3453#issuecomment-339132284

I don't think there's any reason why the JWT should be so large. It might be worth investigating which is the exact cookie that is large, since cookies over 4k are not supported

**Comment by Ferdi** [comment]
@pdpinch same error for me

**Comment by shaidar** [comment]
I was able to reproduce the error (loading the page - https://video.odl.mit.edu/videos/a03d8b4405ca47519e0e/) in Chrome Incognito and tailed the uwsgi logs. The issue is that the collection uuid is incorrect. Talked to @mbertrand about it and possibly having it return a 404 error instead.

**Comment by pdpinch** [comment]
In that case, #350 should fix this?

I'll move it into the ready column and add it to the sprint.

**Comment by mbertrand** [comment]
I can start working on #350 now if that's ok with you @pdpinch

**Comment by pdpinch** [comment]
Working with @blarghmatey, it looks like these manifest as "invalid request block size" errors in the uswgi log on the prod server. 

We found we could reproduce the error by custom crafting a very large cookie. 

Tobias increased the uwsgi buffer size and the error cleared. I can no longer reproduce the error. 

@Ferdi let us know what you find.

**Comment by pdpinch** [comment]
Working for Ferdi now too, so it appears this is fixed.
