### ISSUE TITLE
Success emails do not list course #

### ISSUE THREAD

**Issue by emmello** [mitodl/odl-video-service#328]
Once a video has finished processing, the admin gets "Your video is ready: "Lecture - October 25, 2017" in the subject line and email message, but the course is not listed. If an admin has multiple collections they are moderating, they won't know which video has finished processing.

 The video is also now only listed as the same title in the admin panel, which makes it difficult to identify which lecture is which when there are 4 videos uploaded with the same date.  It needs the course number on both the subject line for the email and in the video title.  Suggest "7.016 Lecture - Oct 26, 2017".

**Comment by pdpinch** [comment]
Can we address this by including the collection name in the success email?

**Comment by pdpinch** [comment]
This may be as simple as modifying the notification e-mail template in the database.
