### ISSUE TITLE
research player failover from YouTube to Cloudfront

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#333]
For public videos (not yet implemented) we have concerns about the cost of cloudfront for popular videos. To avoid cloudfront costs, we would like to offload public streams to services like YouTube. However, not all viewers will have access to YouTube, notably viewers in China and viewers in some US school systems. 

As a workaround, we'd like the video player to start with a a YouTube stream and then failover to a cloudfront (HLS) stream if the YouTube stream fails (for any reason).

**Comment by mbertrand** [comment]
- Due to CORS limitation, will probably need to use the [Youtube data API](https://developers.google.com/youtube/v3/docs/videos/list#try-it) to see if the video can be accessed.

- I've gotten Youtube videos to play with videojs via the plugin but they are not automatically adjusting size to fit in the browser window.

**Comment by mbertrand** [comment]
Multiangle as currently implemented does not work with Youtube.  The Youtube plugin forces the video to play in an iframe, which breaks the multiangle functionality.

**Comment by mbertrand** [comment]
Youtube:
<img width="707" alt="screen shot 2017-10-30 at 10 26 37 am" src="https://user-images.githubusercontent.com/187676/32177434-bf47d526-bd60-11e7-87c5-e573de2040b6.png">

Standard video:
<img width="715" alt="screen shot 2017-10-30 at 10 55 40 am" src="https://user-images.githubusercontent.com/187676/32177523-e7807fd4-bd60-11e7-9651-b4e829a328d5.png">

**Comment by Ferdi** [comment]
@mbertrand I didn't think we'd ever use youtube for multiangle videos ??

**Comment by mbertrand** [comment]
@ferdi Great, I won't worry about it then

**Comment by mbertrand** [comment]
Best approach for now is probably to query the Youtube API to determine if the video is available.  But there is a hypothetical possibility that in some places the 'youtube.com' domain might be blocked but not the 'googleapis.com' domain used by the API.

**Comment by pdpinch** [comment]
I think we can call this issue done. We have some follow up issues:

- [ ] push public videos to YouTube
- [ ] stream public videos from YouTube first
- [ ] remove videos from YouTube when they go private or are deleted
