### ISSUE TITLE
create YouTube channel for ODL video

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#335]
Ideally, we'll need an appropriate account and channel for CI/RC and prod. Videos in the CI/RC channel should be public but unlisted.

**Comment by emmello** [comment]
Do we want to use the TechTV account and change the name?

**Comment by pdpinch** [comment]
Yes on use TechTV account. Not sure about changing the name.

**Comment by emmello** [comment]
Here's the link to the TechTV channel for use with testing:  https://www.youtube.com/channel/UCEGtvnlfAwHya5HvQpl5LeQ

**Comment by emmello** [comment]
Using new OVS-admin@mit.edu Youtube account with this OVS-test channel:

https://www.youtube.com/channel/UCHR16hQQwFjiofh_d-AJcnA
