### ISSUE TITLE
Display permissions options on video edit form

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#342]
Depends on #341 

The edit form dialog for videos should include options for choosing who should be able to view the video.  Mirroring the backend, the options should include:

- 'Collection viewers': the default, meaning the collection view permissions will be used.
- 'Only me': only the collection admin(s)
- 'Everyone': everyone who's allowed to log in to OVS
- 'Moira lists': these will override the collection view lists but not the collection admin lists

Here is a preliminary screenshot (@robhouse what do you think?):

![screen shot 2017-11-01 at 10 58 21 am](https://user-images.githubusercontent.com/187676/32280892-a0052c38-bef3-11e7-9fa4-2932c27e4728.png)

**Comment by Ferdi** [comment]
@mbertrand I think we should discuss a bit more about this.  It's too much for the user to think "who are collection viewers again ??"
Another option would be to keep options in the collection form and video form exactly the same:

Collection form:
Who can view (defaults, you can override each video):
- You
+ Moira lists [list1, list2, list3]
- Public

Video form:  By default shows exactly what user selected on collection form
Who can view
- You
+ Moira lists [list1, list2, list3]
- Public

They can now override the options

What do you think ?

**Comment by mbertrand** [comment]
How about showing who the collection viewers are, which would either be 'Only me' (ie admins) or the moira view lists for the collection (screenshot below).

The problem with getting rid of the 'collection viewers' option and just prepopulating the video moira lists field with collection-level lists is that if the user chooses this option, the lists are then set in stone at the video level and won't update if the collection view lists are changed.  This may not be what the user wants - I think in some/many cases the user will want to the video view permissions to always be the same as the collection view permissions.

![screen shot 2017-11-01 at 12 33 53 pm](https://user-images.githubusercontent.com/187676/32295260-1b80aa60-bf1f-11e7-9b8b-31ead3186208.png)

**Comment by roberthouse54** [comment]
This was why I suggested instead having just two options:
1. "Same permissions as collection"
2. "Override collection permissions"

Or we could even just do this as a checkbox. We could have text that says "Videos by default have the same permission as the collection they are in". The we could have an "Override collection permissions" as a checkbox. (The copy is not great here... )

But the idea is that if the user explicitly checks "override", only then would they be able to set the video permission by radio button: private, moira list, public.

**Comment by mbertrand** [comment]
Approach I'm working on at the moment after talking with @ferdi this morning is to get rid of the 'Same as collection' option.  If no video-specific permissions are set yet, the default choice will be the same as for the collection ("Only me" or "Moira lists" with the same view lists as collection listed).  If the user makes no changes to the default choice, no video-specific permissions will be saved.  If the user selects a different option or changes the default moira lists, video-specific permissions will be saved.  However, I still don't think this is a straightforward way to revert back from video-specific permissions to collection permissions.  Let's say the user happens to change existing video-specific permissions to options that by chance happen to match the current collection permissions.  Does this mean the user just wants to use whatever the collection permissions are or not in this case? Maybe, maybe not.  I think making it explicit that collection permissions are being used or not (either the approach suggested by @roberthouse54 or the 'Same as collection' option) will cause less confusion.

**Comment by roberthouse54** [comment]
OK, so after @Ferdi @mbertrand and I discussed, we are going with the following UI:

![image](https://user-images.githubusercontent.com/20047260/32343330-816f956a-bfd9-11e7-8653-46fe7e268e97.png)

**Comment by emmello** [comment]
Won't the video also still be on OVS in public mode?  Might want to change the text to say "also uploaded to Youtube.com"
