### ISSUE TITLE
Make captions a prerequisite for public videos

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#343]
A video should have an existing caption file before it can be made public.  If the caption file is later deleted, the video should automatically revert back to default collection permissions (after warning the user that this will happen if the captions are deleted).

**Comment by mbertrand** [comment]
@pdpinch @roberthouse54  what do you think of this for the UI side:
- Disable the 'Everyone' permissions option if the video has no captions; add `(Subtitles required)` to that option's text.
- Add a confirmation dialog for deleting subtitles?  If the video is public, warn that it will be reset to  default collection permissions and it will also be deleted from Youtube.

**Comment by roberthouse54** [comment]
That sounds good to me. Here is the screenshot:

![image](https://user-images.githubusercontent.com/20047260/32795340-5e72813a-c939-11e7-912d-86b8850adc1c.png)

The "How this works" link should go to a section on the FAQ page describing how public videos work, although I do not know if this has been written yet.
