### ISSUE TITLE
Allow public video detail/embed pages to bypass Touchstone authentication

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#344]
Videos that are made public should be accessible from URL's that bypass Touchstone authentication (if possible) - for both detail and embed views.

**Comment by pdpinch** [comment]
I'm assuming that we can implement this by NOT requiring authentication for these pages, perhaps by removing the `login_required` decorator from the view, https://github.com/mitodl/odl-video-service/blob/master/ui/views.py#L72

**Comment by pdpinch** [comment]
Tobias says we also need to change the nginx configuration so that only the /login route requires Touchstone.

**Comment by mbertrand** [comment]
@pdpinch the `@login_required` decorator has already been removed from video detail & embed pages, so I think the nginx configuration is all that's left for this one.

**Comment by pdpinch** [comment]
@mbertrand can you do the nginx change, or do you need assistance from @mitodl/devops ?

**Comment by mbertrand** [comment]
I think devops would need to do that (or help me to do that).
