### ISSUE TITLE
push public videos to YouTube

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#347]
Use the Youtube API to upload original video files from S3 to Youtube.

- If the video's permissions are changed to public, initiate a celery task to upload the original video file (S3 -> Youtube).
- Also upload the subtitle file (Videos without subtitles cannot be changed to public)
- Track the Youtube url and status (completed, error, etc) for the video, either in a new `VideoYoutube` model with foreign key to `Video`, or new fields on the `Video` model).
- ~Videos will be uploaded to the channel specified by `settings.YOUTUBE_CHANNEL`~
- Videos will be `unlisted`.
- Youtube API will use the API key specified in `settings.GOOGLE_API_KEY`
- Once the video is uploaded and processed, the subtitles should also be uploaded.  Need a celery task to periodically check the status of `VideoYoutube` objects that have been uploaded but aren't yet done processing.

**Comment by mbertrand** [comment]
- It does not seem possible to specify which channel to upload the video to without a 'Youtube content partner' account.  Videos will just upload to the default channel.
- Only public videos appear in a channel, not unlisted or private videos.
- Service accounts are not allowed to upload videos.  An oauth client id must be created & used.  This requires manual authentication the first time, after which the access and refresh tokens returned can be used to automatically authenticate afterwards (these could be saved as settings).

**Comment by pdpinch** [comment]
Let's discuss further, but here are some follow up thoughts and questions:

> It does not seem possible to specify which channel to upload the video to without a 'Youtube content partner' account. Videos will just upload to the default channel.

@emmello can you look into what it takes to get a content partner account? Jason Player in OCW might be helpful. I'm not sure it's necessary though.

> Only public videos appear in a channel, not unlisted or private videos.

That's fine. The whole point is that we don't want these videos showing up in a channel. We would prefer that people experience them through OVS. 

> Service accounts are not allowed to upload videos.

I'm not sure what you mean by a service account in this context, but it's fine to use a bona fide YouTube account. We already have one in mind, see #335.

**Comment by mbertrand** [comment]
A service account can authenticate without any user input.  Youtube won't allow this for uploads via the API.  The workaround is to manually authenticate one time via OAuth using whatever account is to be used for OVS, then set the access token and refresh token sent in the response as settings in the app.  These tokens can then be used to authenticate automatically from that point on.  This approach is described here (there is also a warning about uploading user videos to a single account, regarding Youtube's quota system): https://stackoverflow.com/questions/37393768/uploading-to-youtube-with-youtube-api-without-users-interaction

I created a django command to step the user through the manual authentication and then print out the token django settings.

**Comment by pdpinch** [comment]
Honestly, this doesn't sound much different from other OAuth flows, like GitHub's.

I see [Google strongly discourages](https://youtube-eng.googleblog.com/2012_02_01_archive.html) our single account approach, but that is from 2012. And I think we're OK with accepting the channel risks at least. If we run afoul of the quota, we can take another approach. 

From Google's 2012 blog post: 

> It’s tempting to design a system in which all videos are uploaded to a single “master” YouTube account, but this is always the wrong approach.

I also found this, quota calculator: https://developers.google.com/youtube/v3/determine_quota_cost

**Comment by emmello** [comment]
It looks like getting partnered means enabling ads onto videos.   https://support.google.com/youtube/answer/72851?hl=en

**Comment by pdpinch** [comment]
Ok, we don't _want_ ads, so I don't think we need to be a content partner for now.

**Comment by mbertrand** [comment]
@pdpinch @emello Youtube does not support the transcoded HLS format, it is actually split up into multiple files per encoding, for example: `video_1504127981867-06dkm600001.ts, video_1504127981867-06dkm600002.ts, video_1504127981867-06dkm600003.ts,` etc.

So the original source video needs to be the one uploaded to Youtube.

**Comment by emmello** [comment]
That shouldn't be too hard to do, should it?  We have the original files, so it makes sense to use that.

**Comment by mbertrand** [comment]
It's easy, I've coded it to use the original file.

**Comment by mbertrand** [comment]
@pdpinch if the user edits the title or description on the video, should those changes also be pushed up to YouTube, and if so should that be part of this issue or a new one?

**Comment by pdpinch** [comment]
We're mostly using YouTube as an alternate streaming source and not it's own publishing platform, so I'm not terribly interested in the title and description on YouTube. 

But yes, in the abstract, those things should be the same. 

Open a separate issue. We can address it when the time comes.
