### ISSUE TITLE
stream public videos from YouTube first

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#348]

**Comment by pdpinch** [comment]
@mbertrand has tested this and it works for regular video, but not for multiangle video. Until we can fix this, we can exempt multiangle videos from YouTube playback (either by streaming from AWS or by preventing them from going public)

**Comment by emmello** [comment]
I would stream them from AWS, as the Math Department now has two collections that they would prefer to be public for the general math community.

**Comment by pdpinch** [comment]
This issue is replaced by #452 (although I note that we still have addressed the issue of public streams of multiangle video)
