### ISSUE TITLE
remove videos from YouTube when they go private or are deleted

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#349]

**Comment by mbertrand** [comment]
Should there be any UI warning to the user that this will happen when they choose to switch the permissions setting for a video from 'public' to something else?

**Comment by mbertrand** [comment]
@pdpinch: @roberthouse54 had a good suggestion of making the Youtube video private (instead of deleting it) if permissions are changed from public to something else.  So if the user later changes their mind and sets it back to public, the Youtube video can be set back to 'unlisted' instead of uploading it again.  What do you think?

**Comment by pdpinch** [comment]
What do you see as the use case here?

I was imagining that when a collection admin switches a video from public to private it is because they are reacting to a copyright or talent release issue. In which case, I think, the goal is to get it off of YouTube. 

But maybe there's another use case?

**Comment by mbertrand** [comment]
Use case is just if someone changes video permissions from public to something else, deliberately or by accident, then changes their mind and wants it public again.  But maybe this would be infrequent enough to not worry about.

**Comment by roberthouse54** [comment]
It just seems to me that if this happens at all, it would be weird to delete the video, re-upload the video, delete the video, etc etc

**Comment by emmello** [comment]
What about this use case:   What if we're removing the video from S3 to save space because it isn't being viewed after a year?  If it's public, we could just leave it on Youtube and people wouldn't get the redirect to OVS.
