### ISSUE TITLE
return 404 when UUIDs are malformed

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#350]
instead of raising an exception like ValueError: badly formed hexadecimal UUID string

https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/396832229/

```
ValueError: badly formed hexadecimal UUID string
(21 additional frame(s) were not displayed)
...
  File "django/db/models/lookups.py", line 156, in as_sql
    rhs_sql, rhs_params = self.process_rhs(compiler, connection)
  File "django/db/models/lookups.py", line 92, in process_rhs
    return self.get_db_prep_lookup(value, connection)
  File "django/db/models/lookups.py", line 182, in get_db_prep_lookup
    [get_db_prep_value(value, connection, prepared=True)]
  File "django/db/models/fields/__init__.py", line 2371, in get_db_prep_value
    value = uuid.UUID(value)
  File "python3.6/uuid.py", line 140, in __init__
    raise ValueError('badly formed hexadecimal UUID string')

ValueError: badly formed hexadecimal UUID string
```

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/396832234/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/396832238/

**Comment by mbertrand** [comment]
@pdpinch I also noticed that bad URL's for collections loads the page with no message that it's an invalid collection.  Instead there's just a grey box with the message 'You have not added any videos yet.  Click the button above...' and no buttons to actually do so.  I can fix that also if okay with you.

Example: https://video.odl.mit.edu/collections/sdkfjsldfkjsd
