### ISSUE TITLE
scrollbar in side menu, in Firefox

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#354]
In Mac Firefox, it looks like the container for my username is too large for the menu, which forces scrollbars. 

<img width="1392" alt="screenshot 2017-11-09 15 58 27" src="https://user-images.githubusercontent.com/430126/32629485-62a56888-c567-11e7-9f07-58b0829cb622.png">

**Comment by emmello** [comment]
I have the same on Chrome, Firefox and Opera on my Windows 8.1 laptop when viewing on the laptop screen which is 2560 x1440 resolution. I do not see the problem with my external monitor, which is an Asus 27" display set to 1080.

**Comment by pdpinch** [comment]
@roberthouse54 can you take a look at this, when you have a chance?

**Comment by pdpinch** [comment]
@roberthouse54 is this still an issue?

**Comment by emmello** [comment]
Yes

![image](https://user-images.githubusercontent.com/1099800/35390356-1f9aa32c-01a9-11e8-927e-43471d1e433f.png)

**Comment by roberthouse54** [comment]
There are 3 sections in the sidebar. Top: username. Middle: channels. Bottom: Help and Log Out links. 

Is this issue about getting rid of the srollbars in the top and the bottom sections? The scrolling in the middle section is intentional.

Robert House
Designer, ODL-Engineering
robhouse@mit.edu

**Comment by pdpinch** [comment]
Good clarifying question. I think we want to fix the top and bottom sections and allow the middle to scroll.
