### ISSUE TITLE
Visualize video view data

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#357]
As a collection owner, I'd like to be able to quickly see how many users have watched my video and where they drop off. 

A visualization similar to what edX does for their [analytics dashboard](https://github.com/edx/edx-analytics-dashboard) would work well:

<img src="https://s.nimbus.everhelper.me/attachment/1241224/c1gtl2hz6xc1lac1dwlf/623857-E1JWS9Gz6usdIO9N/screen.png">

**Comment by mbertrand** [comment]
Some things to look into:
- percent played event for each camera angle
- register default camera angle event on page load
- extraction of video event data via API

**Comment by mbertrand** [comment]
I've experimented with adding the camera angle and percent played to each `timeupdate` label:

![screen shot 2018-01-03 at 11 13 49 am](https://user-images.githubusercontent.com/187676/34528550-3bf45e3e-f077-11e7-902b-5564692248b3.png)

However, there is a potential issue with this approach with 10% intervals: if for example a user watches the section 51%-58% of a movie with the `upperLeft` camera, then at 59% switches over to `upperRight`, the percentPlayed update for 60% will be `percentPlayed 60 upperRight` even though the user played most of that segment with the `upperLeft` camera.  This could be mitigated by using more frequent intervals (every 5 seconds like EdX? Every 1%?).

**Comment by mbertrand** [comment]
Another variation on above: instead of a `timeUpdate` event with label of `percentPlayed XX <cameraAngle>`,  each percentPlayed is an event with the label == cameraAngle:

![screen shot 2018-01-03 at 1 47 45 pm](https://user-images.githubusercontent.com/187676/34534675-12f804a2-f08d-11e7-9f76-737d2f6af00d.png)

![screen shot 2018-01-03 at 1 48 03 pm](https://user-images.githubusercontent.com/187676/34534676-165df7aa-f08d-11e7-9e7a-b5cb8ada7548.png)

@pdpinch @maxliu do you prefer one of these over the other (or prefer something else)?

**Comment by mbertrand** [comment]
PS Here's sample API output using the approach above (events = "10", "20", "30", etc; labels = "upperLeft", "lowerRight", etc).

**Query:**
```python
body = {
    'reportRequests': [
    {
      'viewId': VIEW_ID,
      'dateRanges': [{'startDate': '2017-01-03', 'endDate': '2018-01-03'}],
      'metrics': [
          {'expression': 'ga:uniqueEvents'},
          {'expression': 'ga:totalEvents'}
      ],        
      'dimensions': [{'name': 'ga:eventLabel'}, {'name': 'ga:eventAction'}],
      "dimensionFilterClauses": [
          {
              "filters": [
              {
                  "dimensionName": "ga:pagePathLevel2",
                  "operator": "EXACT",
                  "expressions": ["/a88aa464248a4b668729f3e4538ceb16/"]
              }]
          }, 
          {
              "filters": [
              {
                  "dimensionName": "ga:eventLabel",
                  "operator": "IN_LIST",
                  "expressions": ["upperLeft", "lowerRight", "lowerLeft", "upperRight"]
              }]
          },
          {
              "filters": [
              {
                  "dimensionName": "ga:eventAction",
                  "operator": "IN_LIST",
                  "expressions": ["10", "20", "30", "40", "50", "60", "70", "80", "90", "100"]
              }]
          }             
      ]        
    }]
}
```

**Results:**
```JSON
{
  "reports": [{
    "columnHeader": {
      "dimensions": ["ga:eventAction",
        "ga:eventLabel"
      ],
      "metricHeader": {
        "metricHeaderEntries": [{
            "name": "ga:uniqueEvents",
            "type": "INTEGER"
          },
          {
            "name": "ga:totalEvents",
            "type": "INTEGER"
          }
        ]
      }
    },
    "data": {
      "maximums": [{
        "values": ["1", "2"]
      }],
      "minimums": [{
        "values": ["1", "1"]
      }],
      "rowCount": 23,
      "rows": [{
          "dimensions": ["10", "upperLeft"],
          "metrics": [{
            "values": ["1", "2"]
          }]
        },
        {
          "dimensions": ["10", "upperRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["100", "lowerRight"],
          "metrics": [{
            "values": ["1", "2"]
          }]
        },
        {
          "dimensions": ["100", "upperRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["20", "lowerLeft"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["20", "lowerRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["20", "upperRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["30", "lowerRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["30", "upperRight"],
          "metrics": [{
            "values": ["1", "2"]
          }]
        },
        {
          "dimensions": ["40", "lowerRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["40", "upperLeft"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["40", "upperRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["50", "lowerRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["50", "upperLeft"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["50", "upperRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["60", "lowerRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["60", "upperRight"],
          "metrics": [{
            "values": ["1", "2"]
          }]
        },
        {
          "dimensions": ["70", "lowerRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["70", "upperRight"],
          "metrics": [{
            "values": ["1", "2"]
          }]
        },
        {
          "dimensions": ["80", "lowerRight"],
          "metrics": [{
            "values": ["1", "2"]
          }]
        },
        {
          "dimensions": ["80", "upperRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        },
        {
          "dimensions": ["90", "lowerRight"],
          "metrics": [{
            "values": ["1", "2"]
          }]
        },
        {
          "dimensions": ["90", "upperRight"],
          "metrics": [{
            "values": ["1", "1"]
          }]
        }
      ],
      "totals": [{
        "values": ["23", "30"]
      }]
    }
  }]
}
```

**Comment by mbertrand** [comment]
- Use 10-second time intervals
- Each interval is its own event, with a label equal to the camera angle. (event 10, label 'upper left'; event 2500, label 'lower right', etc).

**Comment by pdpinch** [comment]
We met today and decided a few things:

1. Events should be triggered on a consistent time interval (e.g. 10s) instead of percent played. 
2. We shouldn't overload the event fields with multiple values (as suggested in https://github.com/mitodl/odl-video-service/issues/357#issuecomment-355054185). 
3. The OVS app will send events to Google Analytics (as it does now)
3. The OVS app will fetch the aggregate data from the Google Analytics API for visualization.
4. Matt will look into the [bokeh library](https://bokeh.pydata.org) for visualization.

**Comment by mbertrand** [comment]
In terms of visualization libraries, [Dash/plot.ly](https://plot.ly/products/dash/) also looks promising:
https://medium.com/@plotlygraphs/introducing-dash-5ecf7191b503

**Comment by mbertrand** [comment]
How interactive should the graph be? For example, should the user be able to specify a date range? Or will it be a static graph that shows all available data within a fixed time frame (or all available data since the video was uploaded)?

**Comment by emmello** [comment]
I think a date range would be good in case they want to see the number of views around an exam time, but that is me speaking on behalf of the users.

**Comment by mbertrand** [comment]
After talking with @Ferdi :
- Use 1-minute intervals
- Start out with a simple static graph showing all available data for a video (ie since it was uploaded).
- Look into options for sending video id independent of the URL for all events.

**Comment by mbertrand** [comment]
@Ferdi @pdpinch, I can send the video id by setting up a 'custom dimension' in google analytics (there are 20 available for a typical account).  This requires that the dimension be set up manually first for the correct account within GA.  Then the name of that dimension (`dimensionX`, where `X` is a number between 1 and 20) would need to be set in the django settings and passed on to the front-end. 

![screen shot 2018-01-09 at 2 03 23 pm](https://user-images.githubusercontent.com/187676/34738148-1c9b31d8-f546-11e7-9f5e-415c4d51c837.png)

The `secondary dimension` would still need to be applied in GA to view it:

![screen shot 2018-01-09 at 2 02 59 pm](https://user-images.githubusercontent.com/187676/34738159-273d6d72-f546-11e7-8afc-585a1381236a.png)


However, this would only be useful if the URL structure for videos changes in the future, since the video id is included in the URL.

**Comment by pdpinch** [comment]
@mbertrand let's talk about cleaning up this issue and breaking it down into sub-tasks.

**Comment by pdpinch** [comment]
I'm moving this back to the backlog, since we're only focussing on #401 for now.

**Comment by adorsk** [comment]
Closing this epic, as the issues for this epic have been closed, and video analytics is now being tracked by other issues.
