### ISSUE TITLE
Some emails cause Moira to throw exceptions when queried

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#370]
Some non-MIT emails cause java NullPointerExceptions when querying Moira for that user's lists:

[redacted]

**Comment by mbertrand** [comment]
https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/380406074/activity/

**Comment by mbertrand** [comment]
Caused when users are not associated with any moira lists.  Proposed solution is to catch exceptions from Moira when submitting the `user_lists` request, examine the stack trace for a java NullPointerException, and if present return an empty set of moira lists instead of raising the exception.

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/380406074/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/420554208/
