### ISSUE TITLE
FAQ typo - Viewer FAQ

### ISSUE THREAD

**Issue by emmello** [mitodl/odl-video-service#371]
Typo in answer to I see 0 videos in my collection.  Where is my video"

Typo:  Check with your professor to make sure you have access to the course collection so you cna se ethe videos.

Should be:  Check with your professor to make sure you have access to the course collection so you can see the videos.

**Comment by emmello** [comment]
This one can also be revised - refers to the old USwitch player for speed control:


How can I play back the video at a faster speed?

Existing:
On the lecture capture videos, click the gear icon on the toolbar. Select Speed, and then pick the speed you would like to use.

Change to

Hover mouse over the 1X on the toolbar and select the speed you would like to use.

**Comment by pdpinch** [comment]
closing this in favor of #379
