### ISSUE TITLE
Change Copy in FAQ page, and group questions in sections

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/odl-video-service#379]
We want to add sections on the FAQ page, and also change the copy. The design showing sections is below. 

The copy for the page is here:
https://docs.google.com/document/d/1xTCvERia90_8pvcI9iUvZz_Jm27xGscc9cJOXXQzQKc/edit?usp=sharing

![faq_new](https://user-images.githubusercontent.com/20047260/33447079-1e57a1d6-d5d0-11e7-8f27-7567e8003409.jpg)

**Comment by mbertrand** [comment]
The current FAQ shows different questions for viewers vs admins.  Should some of these sections display only for admin users ("Uploading Video and managing Collections", "Automated Video Lecture Capture") or will everyone see the same FAQ?

**Comment by pdpinch** [comment]
Let's keep this simple and make everything viewable. 

Today's viewer might be tomorrow's admin.
