### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#388]
Draft copy at https://docs.google.com/document/d/1vLb3-_NFT6BgbGFdjjRF4NhVqp6Ay2eDSFLbafigjK4/edit#heading=h.9ra1j7m82h9r

Note that the TOS is broken into two sections: a short summary in bullet form and then a longer body of legalese.

**Comment by pdpinch** [comment]
proposed location:

- footer
- end of the FAQ
- it would be nice to put it near the upload button

**Comment by roberthouse54** [comment]
![tos_on_faq](https://user-images.githubusercontent.com/20047260/34529644-b1d20f22-f07a-11e7-8395-57146651f073.png)

![tos_in_footer](https://user-images.githubusercontent.com/20047260/34529647-b53ab6f0-f07a-11e7-8d21-c503a5b98cf4.png)

![tos_page](https://user-images.githubusercontent.com/20047260/34529649-b8c1f9a0-f07a-11e7-84e1-9f24160b0f1f.png)

**Comment by mbertrand** [comment]
A couple questions:
- The issue mentions `"Terms of Service"` but the draft has a title of `"Terms of Use"`, should they be consistent?
- There is a `"Last updated on"` section in the draft: should that appear on the page and if so, is there a particular date I should enter?

**Comment by mbertrand** [comment]
@roberthouse54 @pdpinch how does this look for a link near the upload button?

![screen shot 2018-01-12 at 1 29 16 pm](https://user-images.githubusercontent.com/187676/34889613-9fc4e9d4-f79c-11e7-8507-73492ed635a8.png)

**Comment by roberthouse54** [comment]
If we really need to do this I would say add some margin between the button and the link.

**Comment by pdpinch** [comment]
Let's change it to "Terms of Service"

@roberthouse54 I'm open to alternate suggestions about how to associate the terms of service with the upload process. This isn't a legal requirements (not that I've consulted anyone).

**Comment by emmello** [comment]
On TechTV, there was a physical checkbox that you had to click through before being allowed to upload the video.  Of course, that doesn't actually mean people read it, but much like a EULA notice, there is some level of acknowledgement that they should have read it before uploading.
