### ISSUE TITLE
Update GA events to allow vizualization

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#401]
In order to present and visualize analytics data to collection admins (#402) we need to make sure we are collecting the necessary event data. 

### acceptance criteria 
- [x] fire events every 1m (60s)
- [x] `eventCategory` set to "video"
- [x] `eventAction` set to a string with the format "Ttttt" where tttt is the minute of the video when the event is fired 
- [x] `eventLabel` set to the video uuid
- [x] `customDimension1` set to the camera angle (if this works)

**Comment by mbertrand** [comment]
@pdpinch @Ferdi Just a thought - camera angles right now are labelled as `upperLeft`, `lowerRight`, etc, based on their position in the raw video as a whole: [+]  However, on the OVS video page, the camera angles are displayed in a vertical column. Would it be more user-friendly to refer to the angles by number from top to bottom: 1,2,3,4?

**Comment by Ferdi** [comment]
Sounds good to me.

**Comment by mbertrand** [comment]
@pdpinch there is a way to create a custom dimension via API for Google Analytics (where camera angle will be stored), should I code something up for that or would you prefer to just create it manually (`Admin` -> `Custom Definitions` -> `Custom Dimensions` -> `New Custom Dimensions`):

<img width="317" alt="screen shot 2018-01-10 at 1 15 18 pm" src="https://user-images.githubusercontent.com/187676/34795064-c8486acc-f61e-11e7-9435-7154cdbbdab2.png">

**Comment by pdpinch** [comment]
Code is always better. 

Is there a way for you to test whether the custom dimension exists and then create it if it doesn't?

> @pdpinch <https://github.com/pdpinch> there is a way to create a custom dimension via API for Google Analytics (where camera angle will be stored), should I code something up for that or would you prefer to just create it manually (Admin -> Custom Definitions -> Custom Dimensions -> New Custom Dimensions):

**Comment by mbertrand** [comment]
Yes, there's a way to do that.  OAuth2 authentication is required though, so that will need to be set up along with settings to store all the required tokens/keys; the tracking id isn't adequate.

**Comment by pdpinch** [comment]
Hm. That's a lot of overhead. I'm not sure it's worth the effort. 

What's the failure mode for the events if the custom dimension isn't configured properly. Does it drop the entire event, or does it just lose the custom data, or... ?

**Comment by Ferdi** [comment]
I thing you'd need to do that to query GA data at some point.  But , I agree, manual is fine for now.

**Comment by mbertrand** [comment]
I also agree, seems like a lot of work for something that only has to be done once, and takes < 1 minute to do manually.  But @Ferdi is right that OAuth will need to be set up eventually anyway to create the view charts.  

If the custom dimension doesn't exist, the events are still sent to the server and are registered, but the camera angle info will be lost.
