### ISSUE TITLE
Present video analytics visualization & data for collection admins

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#402]

**Comment by adorsk** [comment]
## Querying Google Analytics: On-demand vs. Pre-queried

When should we pull data from Google Analytics (GA)?

A. At the time a user goes to the 'analytics' detail view in OVS. ("on-demand")
B. Some time before a user goes to the 'analytics' detail. ("pre-queried")

### Pros/Cons for On-Demand

#### Pros
 - no need to store GA data in OVS db. 
 - no need to write/maintain cron job to query from GA.

#### Cons
 - User has to wait for query to GA to resolve. (this is not really an issue. GA is fairly zippy, on the order of a few seconds at most).

### Pros/Cons for Pre-Queried

#### Pros
 - No need to wait for GA. (again, this is not a long wait)

#### Cons
 - need to store GA data in OVS db. 
 - need to write/maintain cron job to query from GA.

With the above pros/cons in mind, on-demand is the simpler way to go.

**Comment by adorsk** [comment]
A possible Implementation plan:

1. Write a utility function in the ovs django app to query GA. Perhaps Something like this:

  ```
  def get_video_analytics_data_from_ga(video_id, timespan=None):
    # oauth dance...
    # execute analytics query...
    # format data...
    return video_analytics_data
  ```

2. Write an endpoint that proxies to the utility function.
3. Write front-end logic that renders the analytics data the endpoint returns.

Other considerations:

1. We could render charts/tables (or whatever other vizzes we want) in the backend. But imho it is better to do this on the front-end, for:
   1. better dx.
   2. flexibility to add other interactions (selecting date range, filtering tables, etc.)

**Comment by mbertrand** [comment]
@adorsk all the above sounds good!  If it turns out that on-demand queries are too slow then we can switch to another approach.

**Comment by roberthouse54** [comment]
There are tabs to view either a graph or table. We do not need pagination on the table, as most should have <100 rows. We will add a link to the analytics page next to the other links on the Video Details page. The overflow menu on the collection page will also have a link to the analytics page.

![image](https://user-images.githubusercontent.com/20047260/37681484-30008a4a-2c5d-11e8-81e8-5140992d3ae1.png)

![image](https://user-images.githubusercontent.com/20047260/37681508-45d2bb68-2c5d-11e8-9d28-70f3a7f200fd.png)

![image](https://user-images.githubusercontent.com/20047260/37681553-64ba80ce-2c5d-11e8-8d6e-bfec7a19c982.png)

![image](https://user-images.githubusercontent.com/20047260/37681563-6b8a5406-2c5d-11e8-8fb3-fbc084ff9678.png)

**Comment by adorsk** [comment]
Pros/Cons of viz libraries considered for this feature.

### Vega
#### Pros
1. A lot out of the box.
2. Many examples.

#### Cons
1. The out-of-the-box chart probably wasn't close to what we wanted.
2. A lot of work to customize.
3. Somewhat heavy (larger extra libs)

### Plotly.js
#### Pros
1. A lot out of the box.
2. Many examples/docs.
3. Easier to customize than vega.

#### Cons
1. Very heavy. Library is a kitchen-sink library that includes many features we don't need.
2. Can customize most things. But a lot of work to customize the remaining things.

### Plain D3
#### Pros
1. Many examples/docs.
2. Can customize as much as you want.
3. Lightweight: just pick what you use.

#### Cons
1. You end up having to write boilerplate for basic things like axes, tooltips.

### VictoryCharts
#### Pros
1. Many examples/docs.
2. Can customize as much as you want.
3. Lightweight: just pick what you use.
4. Saves boilerplate for common uses (axes, tooltips)

#### Cons
1. None I can think of.

Not surprisingly, I used VictoryCharts.
