### ISSUE TITLE
Keys missing from .env.example

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/odl-video-service#409]
These keys are required by the app but missing from this file:

- `MAILGUN_KEY`
- `MAILGUN_URL`
- `VIDEO_S3_WATCH_BUCKET`

Also, these keys are in there twice:

- `MIT_WS_CERTIFICATE`
- `MIT_WS_PRIVATE_KEY`

**Comment by adorsk** [comment]
Several other keys as well.

Self-assigning this issue, as a reminder to update based on recent work in this project.
