### ISSUE TITLE
create S3 bucket(s) for TechTV legacy data

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#411]
In order to have a clear distinction between legacy data and OVS-native data, we'll keep them in separate buckets.

**Comment by pdpinch** [comment]
@mbertrand this should be constructed similarly to the OVS's existing buckets. Does that mean separate buckets for video, thumbnails and captions?

**Comment by mbertrand** [comment]
Yes.  There' also separate buckets for original and transcoded videos in OVS, but the TechTV videos won't be re-transcoded so one video bucket for TechTV should be enough.

**Comment by mbertrand** [comment]
Suggestions for bucket names, feel free to modify (environment=ci, rc, prod):

`odl-video-service-techtv-<environment>`
`odl-video-service-techtv-thumbnails-<environment>`
`odl-video-service-techtv-subtitles-<environment>`

Cloudfront will also need to be set up with the above.  I don't think there can be more than 1 bucket associated with a cloudfront path, so maybe the paths for these could be prefixed with `techtv`, for example `techtv/thumbnails`

**Comment by mbertrand** [comment]
Also `odl-video-service-techtv-transcoded-<environment>` (to transfer the previously transcoded `small`, `basic`, `medium`, and `large` vide files from TechTV into).

**Comment by mbertrand** [comment]
Cloudfront URL's should also be mapped to S3 buckets (devops).  For example:

<img width="483" alt="screen shot 2018-01-23 at 3 54 04 pm" src="https://user-images.githubusercontent.com/187676/35300186-bc67b348-0055-11e8-8afa-ddc014e3ef37.png">

**Comment by mbertrand** [comment]
@pdpinch @emmello what do you think of using the existing buckets instead of new ones, as long as the S3 object keys for all TechTV files have a prefix of `techtv`?  This would make them easy to differentiate from standard OVS objects without the need for separate buckets. 

For example, a TechTV thumbnail would have an S3 key of `techtv/thumbnails/<video_id>/001.jpg` while a standard OVS thumbnail would have an S3 key of `thumbnails/<video_id>/001.jpg`.

The Cloudfront distribution would still need to be updated to map these prefixes to the appropriate S3 buckets.

**Comment by pdpinch** [comment]
Ok, this will save us some effort with managing credentials. I'll close the issue.

**Comment by mbertrand** [comment]
@pdpinch @shaidar @blarghmatey Cloudfront behaviors still need to be configured for TechTV prefixes in the current S3 buckets, something like this (they should have precedence over the existing behaviors):

<img width="587" alt="screen shot 2018-02-01 at 12 24 29 pm" src="https://user-images.githubusercontent.com/187676/35693061-090c6a4e-074b-11e8-8a4b-0471247f429e.png">

**Comment by mbertrand** [comment]
Actually never mind, I can use path patterns like`thumbnails/techtv`, `transcoded/techtv` instead, so nothing will need to change.
