### ISSUE TITLE
migration script to create collections, videos from techTV data

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#415]
### acceptance criteria
- [x] create private collection in OVS for each protected collection in TechTV
- [x] migrate TechTV collection id, name, description, permissions
   we will flatten TechTV collection hierarchy, including any necessary calculation of permissions
- [x] migrating permissions will require creating corresponding moira list objects in OVS
- [x] migrate video id, name, description, file locations (anything else?)

### questions
- [ ] Do we need to address nested moira lists in order for this to work?

**Comment by mbertrand** [comment]
Moira list objects for the collections will also need to be created and associated with the collections as part of this process.

TechTV moira lists are based on the collection id and name.  For example if the collection name is `Energy and Clean Tech Series` and id is `2383`, the moira lists will be `techtv-2383-energy-and-clean-tech-series-owner` (admin) and `techtv-2383-energy-and-clean-tech-series` (view).  There is also a 'collaborator' list, which can be ignored.  Nested lists are a problem, should look into seeing if there's a reliable way to detect them and add them to the view or admin lists.

The collections database table has a `protected` field, and the videos table has a `private` field.  The current behavior seems to be:
- Public videos, protected collection: require touchstone login to view.
- Public videos, unprotected collection: anyone can view, no login required.
- Private videos: only owner can view, but there is a special link that allows anyone with it to view.

@emello and @pdpinch should permissions be imported as follows?:
- All imported collections will require touchstone login see the collection page, protected or not.
- All public videos from protected collections will require touchstone login to view.
- Public videos in unprotected collections will have video-specific permissions set to public.
- Private videos will have video-specific permissions set to owner only.

**Comment by pdpinch** [comment]
@mbertrand we won't be migrating unprotected collections at this time. Otherwise your permission mapping seems correct.

**Comment by pdpinch** [comment]
@mbertrand I updated the description to reflect our current thinking. It may still need some more detail.

**Comment by mbertrand** [comment]
Initial thoughts on how the migration script would work:
-  for each S3 bucket prefix specific to a video (such as `044bc0080f75ac15c6129816c517ccfa`):
    - look up the video in the MySQL database based on `external_id` which will match the bucket prefix.
    - look up the collection for that video in the MySQL database
    - look up the owner for that collection in the MySQL database
    - recreate the user for that owner in OVS if necessary (#414)
    - create a `Collection` object in OVS if it doesn't yet exist.  
      - Additional fields may need to be added to be able to map old to new collections and their URL's.
    - based on the collection name and id, create `MoiraList` objects (admin and view) and associate with the `Collection` in OVS.
    - create a `Video` object in OVS, setting video-specific permission appropriately if necessary
      - Additional fields may need to be added to be able to map old to new videos and their URL's.
    - create a `VideoFile` object in OVS for the original video if present (S3 key ending with `original.<extension>`)
    - generate a JSON file containing info on the multiple resolution sources available for the video (`small.mp4`, `hd.mp4`, etc) and upload to the TechTV transcoded bucket where those video files exist.  This will be used as the playlist for VideoJS (part of #413)
    - create a `VideoFile` object in OVS for the above playlist (as opposed to the usual m3u8 HLS playlist).
    - Search for 'jumbo' size thumbnails in the TechTV `static` S3 bucket with the video's prefix in the key.  Create a `VideoThumbnail` object in OVS for each one. 
    -  Search for converted VTT caption files in the appropriate bucket. Create a `VideoSubtitle` object for each one.

**Comment by emmello** [comment]
I think Ferdi would like me to be the default owner of any TTV collection as it is possible that the original owner is no longer at MIT.  If it is possible to query the Data Warehouse we might be able to port over the original owner, but there's also a chance they are no longer in the same dept and that ownership needs to move elsewhere.

**Comment by mbertrand** [comment]
@emello that should make things easier, and in that case #414 probably isn't necessary anymore.

**Comment by emello** [comment]
Hi Matt,

Not sure how became part of this project. I believe you are reaching out to the wrong person.

Thanks,
Elcio

**Comment by mbertrand** [comment]
Create a TechTVMigration model to track each video's migration status, something like:
```python
class TechTVMigration(models.Model):
    techtv_id: models.IntegerField()
    ovs_key: models.UUIDField()
    subtitle_import_status: models.CharField()
    thumbnail_import_status: models.CharField()
    videofile_import_status: models.CharField()
    errors: models.TextField()
```

**Comment by mbertrand** [comment]
@emmello I did a test-run of walking through the videos and came up with a few questions:
 - does the `videos.file_restored` field reliably indicate that the videos still exist on S3?  Or is this just to flag videos that were deleted and restored?
 - Is it safe to ignore any videos whose `status` != `uploaded`?
 - There's some videos that have no `external_id`'s, which is what I plan to use to find the correct S3 objects for the video files & thumbnails.  All of these also have `file_restored` = 0, all but 4 have no title & description, all have no external urls.  Is it safe to ignore these too?

PS This is all based on the MySQL backup file on dropbox, from last November.

**Comment by mbertrand** [comment]
[Moved from wrong issue]

@pdpinch @emmello TechTV descriptions sometimes have HTML formatting, which currently just renders as plain text (screenshot).  I can modify the React code to display it as HTML, but there is some security risk in allowing people to enter their own HTML in this field.

<img width="605" alt="screen shot 2018-02-01 at 9 29 26 am" src="https://user-images.githubusercontent.com/187676/35683681-c237b438-0732-11e8-9f42-01b100f31756.png">

**Comment by pdpinch** [comment]
Is the HTML limited to OCW collections? If it is, then I think we can ignore it and continue to render as text.

**Comment by pdpinch** [comment]
@mbertrand should this be moved to "In Progress" ?

**Comment by mbertrand** [comment]
@pdpinch sure but that option isn't shown to me in github anymore, not sure why.

**Comment by emmello** [comment]
@mbertrand @pdpinch   Sorry I missed this, I never got an alert for these, but am responding now.  

1. The videos.file_restored should reliably relate to the video being restored to S3.  The only variance I can see there is if for some reason we deleted the video or the collection owner deleted the video.

2. Is it safe to ignore any videos whose status != approved?    Yes

3. There's some videos that have no external_id   - If there's no external_id, there is no MD5 folder.  Safe to ignore, given these are probably bad uploads that got caught in the Transcluster queue and probably would re-uploaded.  

4. HTML can be either in the Collection description or Video description (see example)  I don't think we need to keep this when we move stuff over.  If we need it, we can get it out of the original DB:

![image](https://user-images.githubusercontent.com/1099800/35868794-94b5fbc6-0b2b-11e8-94d4-085a0764436f.png)

**Comment by mbertrand** [comment]
@blarghmatey is it possible to set up a temporary RDS instance of MySQL with the latest TechTV data, that this migration script can connect to from RC and production?
