### ISSUE TITLE
migrate caption files and convert SRT to VTT

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#416]

**Comment by mbertrand** [comment]
TechTV caption files are stored on the TTV production server and DE server, not on S3.  Copies are also available on Dropbox.

Assuming Dropbox is up-to-date with the latest files, the easiest way to transfer these to OVS is probably via Dropbox API to S3.

**Comment by mbertrand** [comment]
@emmello I ran a query to get the caption filenames for approved videos in protected collections, based on the MySQL backup from 11/17.  There's 55 returned but < 10 of them are in dropbox.

**Comment by pdpinch** [comment]
@mbertrand did you tell me that _none_ of the protected collection contain videos with captions?
