### ISSUE TITLE
migrate thumbnails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#417]

**Comment by mbertrand** [comment]
@emmello  are the thumbnails that should be transferred stored in S3?  I noticed that there are `thumbnail_url` and `external_thumbnail_url` fields in the `videos` database, but on the TechTV page for the video the thumbnmail URL is from cloudfront.

For example, for video id 531:
- `thumbnail_url`: http://cdn-thumbs.viddler.com/thumbnail_2_1405b4ad_v1.jpg (placeholder image)
- `external_thumbnail_url`: http://cdnbakmi.kaltura.com/p/203822/sp/20382200/thumbnail/entry_id/1_loqo2owv/version/100000 (small image)
- `thumbnail_file_name`: `placeholder.jpg`

On the video's URL of http://techtv.mit.edu/videos/531-ai-lab-cog-the-humanoid-robot, the thumbnail shown has a URL of https://duqmab81lwd47.cloudfront.net/6097c15a226bfbb478b0bfade55ec0d2/thumbnails/531/thumb.jpg (and is pretty small).

**Comment by emmello** [comment]
@mbertrand  Techtv thumbnails are in ttv_static on AWS.

**Comment by pdpinch** [comment]
@mbertrand should this be moved to "In Progress" ?
