### ISSUE TITLE
Modify collection/video permissions to account for nested moira lists

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#422]
Currently, permission to view a collection/video is determined by looking for overlap between the moira lists a user belongs to and the moira lists the collection/video is associated with.  This allows for fast retrieval of all the collections accessible to a user, but fails to account for nested moira lists.

Retrieving all the collections a user has access to should probably continue to use the above permissions strategy, but when on an individual collection or video detail page, the permissions check should run `moira_client.list_members()` for each associated moira list; this will return nested users.

**Comment by pdpinch** [comment]
so you're saying we need two different strategies, one for looking up all the collections a user has access to and another one for determining if a user can view a specific page?

**Comment by mbertrand** [comment]
Yes

**Comment by mbertrand** [comment]
@pdpinch @emmello TechTV descriptions sometimes have HTML formatting, which currently just renders as plain text (screenshot).  I can modify the React code to display it as HTML, but there is some security risk in allowing people to enter their own HTML in this field.

<img width="605" alt="screen shot 2018-02-01 at 9 29 26 am" src="https://user-images.githubusercontent.com/187676/35683681-c237b438-0732-11e8-9f42-01b100f31756.png">
