### ISSUE TITLE
TechTV video/collection descriptions contain HTML

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#428]
About 80 videos, 13 collections in TechTV contain some HTML in their descriptions, including hyperlinks.  These will currently display as plain text.  Options for dealing with this include:

- Strip out the HTML code.  
    - How to deal with hyperlinks: remove the link text and just leave the URL?
- Display descriptions as HTML but strip out any HTML tags entered by users in the edit form.

**Comment by pdpinch** [comment]
Ferdi and I discussed. We'd like to make sure OVS only has text descriptions, so let's just strip the HTML. 

If necessary, @emmello can review and clean up anything that looks too bad.
