### ISSUE TITLE
Add sorting and filtering to EncodeJobs in the admin console

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#442]
When trying to determine the cause of any transcoding errors, it would be useful to:
- have the EncodeJob objects sorted in descending order by creation date, with newest first.  
- search for an EncodeJob by video key
- filter by status

**Comment by pdpinch** [comment]
If an encode job fails, we'll still get a video object, right?

**Comment by mbertrand** [comment]
Yes, the Video object is created first, before uploading and transcoding tasks begin.
