### ISSUE TITLE
'Only me' permission is confusing if set by a user who is not the owner

### ISSUE THREAD

**Issue by noisecapella** [mitodl/odl-video-service#444]
To reproduce:
 - create a collection
 - change the edit permission on the collection to the `odl-engineering` moira list
 - create a user who is on that moira list and log in as them
 - As that user change the permission of the collection to 'Only me'

'Only me' makes me think it will reassign the ownership to the logged in user. Instead we should change the text to 'Only the owner'`, at least for other users

**Comment by pdpinch** [comment]
@mbertrand does "only me" == "only the owner" ? 

cc: @roberthouse54
