### ISSUE TITLE
Change default bitrate to be highest instead of lowest

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#458]
As a lecture video viewer, I want to see a high quality video where the text is legible. 

Most of our users are on campus, with access to MIT's high speed network. To avoid complaints about low-quality "blurry" video, we should default to the highest bit rate and only decrease the bitrate if the network is too slow. Especially important for multiangle videos where we are pixel-doubling a quarter-resolution video.

**Comment by mbertrand** [comment]
I've come up with a quality selection function that selects the highest quality video whose bandwidth is less than the available connection bandwidth, and ignores the dimensions of the video in the browser.  I can also force it to play the highest quality available for the first X (5? 10?) seconds regardless of available bandwidth if you'd like.  Does that sound okay?

**Comment by mbertrand** [comment]
Elaine would like the highest quality played automatically, regardless of bandwidth, for the first 10 seconds.
