### ISSUE TITLE
raise to Sentry when copying to AWS fails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#462]
See the [thread in Slack](https://mitodl.slack.com/archives/G5T80SA7L/p1520612987000634):

This error appears in the logs:

```
[2018-03-09 16:45:19,000: ERROR/ForkPoolWorker-3] cloudsync.tasks.monitor_watch_bucket[05dd3d90-25a4-4e93-b9b4-5ade645aa313]: AWS error when ingesting file from watch bucket MIT-MIT-Math FC-lec-mit-0000-2018mar08-1635-MM.mp4: {'source_url': ['Enter a valid URL.']}
```

But it didn't get raised to Sentry. It would be nice to be notified about errors like this.

**Comment by mbertrand** [comment]
The `monitor_watch_bucket` task should be modified to collect any error that occurs for each file to be processed, and raise an exception after iterating through all the files in the bucket if any errors occurred.  Currently it just logs the exceptions without raising them.

**Comment by mbertrand** [comment]
Just discussed this with @rhysyngsun, it seems that Sentry should be monitoring the logs and sending alerts for any logged exceptions, so it shouldn't be necessary to raise them.  They are configured the same in django:

```python
        'sentry': {
            'level': SENTRY_LOG_LEVEL,
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
            'formatter': 'verbose'
        },
```

```python
SENTRY_CLIENT = 'raven.contrib.django.raven_compat.DjangoClient'
RAVEN_CONFIG = {
    'dsn': get_string('SENTRY_DSN', ''),
    'environment': ENVIRONMENT,
    'release': VERSION
}
```

**Comment by pdpinch** [comment]
This is the issue where I miswrote the title. I want to see Sentry notify on failures when copying files *_to_* AWS.

**Comment by mbertrand** [comment]
Some logged celery errors result in Sentry alerts:
- [cloudsync.tasks.remove_from_youtube](https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/499383736/?query=is:unresolved) (RC)

I've also seen a couple of other Sentry events where a logged `monitor_watch_bucket` error shows up in the collapsed breadcrumbs but doesn't seem related to the actual event, for example:

https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/474682423/

<img width="690" alt="screen shot 2018-03-22 at 2 04 27 pm" src="https://user-images.githubusercontent.com/187676/37789323-f9710468-2dd9-11e8-9357-8f9bff3474db.png">

<img width="669" alt="screen shot 2018-03-22 at 2 37 08 pm" src="https://user-images.githubusercontent.com/187676/37791048-9265f80a-2dde-11e8-8f82-01360a11cdd4.png">


After some experimenting, it seems that Sentry will report raised errors from this task, but not logged errors.  It does show the logged errors in the breadcrumbs though, so it doesn't seem like they're invisible to Sentry.  It just doesn't send alerts about them.

https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/501218623/

**Comment by mbertrand** [comment]
Figured it out, the culprit is the logger type.  Changing from `celery.get_task_logger()` to `logging.getLogger()` resolves the issue.
