### ISSUE TITLE
add server status end-point for checking application certificate

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#487]
As a devops, I'd like to have automated checking for the moira app certificate expiration so I don't find out the certificate expired from end users.

We should add an endpoint that exposes the cert's expiration date. The obvious place to add this would be the django-server-status project, so this is blocked by https://github.com/mitodl/django-server-status/issues/33

**Comment by amir-qayyum-khan** [comment]
First step:
https://github.com/mitodl/django-server-status/pull/34

Next step:
Update `HEALTH_CHECK` settings in odl video to add `'CERTIFICATE'` key

**Comment by pdpinch** [comment]
@mitodl/devops can update this setting and update monit?

**Comment by pdpinch** [comment]
@mitodl/devops can this be closed?

**Comment by shaidar** [comment]
[OVS Beacon](https://github.com/mitodl/salt-ops/blob/master/pillar/beacons/http_status_odl_video_service.sls) deployed.
