### ISSUE TITLE
squished folder icons in mobile 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#488]
When I view the collections pages on my iPhone, I get the following:

![img_5585](https://user-images.githubusercontent.com/430126/37940738-525a1d06-3138-11e8-8f3e-a53e7fcf02bd.PNG)

**Comment by pdpinch** [comment]
@roberthouse54 does #491 fix this?

**Comment by roberthouse54** [comment]
Yes, I forgot to close it.
