### ISSUE TITLE
Test private techtv.mit.edu with OVS back-end

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#489]
Before we switch over the TechTV DNS, we need to manually test private URLs. 

1. On the test machine, change the /etc/hosts file to map techtv to the OVS IP
2. Visit an original TechTV URL
3. Confirm:
  a. login required 
  b. comparable OVS page loads
  c. video plays

**Comment by emmello** [comment]
On the test machine, change the /etc/hosts file to map techtv to the OVS IP
Visit an original TechTV URL
Confirm:
a. login required  **Confirmed**
b. comparable OVS page loads  **Unconfirmed for non-admin account**  - tested with using emello@capellauniversity.edu collaborative account (which is on the ovs-mvp-access list)  Once logged in, I see for techtv.mit.edu/videos/9ceb926eda9de46e56086b12f3c591d0cb31635a/private that I do not have permission to play the video.   Will try later to see if it is a moira sync issue with RC
c. video plays

**Comment by emmello** [comment]
Touchstone Collaboration account now works fine.

**Comment by pdpinch** [comment]
@emmello @mbertrand do you think we can close this?

**Comment by emmello** [comment]
@pdpinch  Fine with me.  I was able to test all items.
