### ISSUE TITLE
Limit video upload to django staff

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#5]
At this time, we want to limit access to uploading videos (and creating collections) to only MITx affiliates. The easiest way to do this to limit access to users with the django staff role. Elaine or Peter can take responsibility for adding users as necessary. 

At some point in the future, we may want to use a moira list to maintain these access controls.

**Comment by Ferdi** [comment]
Yes, if they pass touchstone login , they can upload videos . Right @pdpinch  ?

**Comment by pdpinch** [comment]
We're going to need some kind of authorization, because anyone can get a TouchStone collaborator account. 

Let's talk and then I'll update the issue.

**Comment by mbertrand** [comment]
Related question: If a video is restricted via moira, should a user who isn't in the appropriate moira list still be able to visit the video's detail page and read the title, description etc, but just not be able to view the video?

**Comment by pdpinch** [comment]
I updated the description to reflect the feedback we got from the Product Council.

**Comment by mbertrand** [comment]
@pdpinch non-staff users who are admins for a collection (via moira_list) should still be able to upload to that collection, right?  It's just creating collections that should be restricted to staff users (or superusers)?

**Comment by Ferdi** [comment]
@pdpinch @mbertrand I thought we'd do this via a special moira list ?

**Comment by pdpinch** [comment]
I assumed that using staff was faster to code. If that's not the case, we should go with a moira list because that is the eventual goal (as mentioned in the description).

**Comment by mbertrand** [comment]
Using staff was easy to code.  Using a moira_list would be slightly more effort but not too bad, would need another setting to specify which moira list to use.
