### ISSUE TITLE
As a viewer, I would like to be able to view a private video that I have permission to view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#53]
When viewing videos, access to the video stream should be controlled by moira permissions applied to the video channel. 

Depends on mitodl/mit-moira#1 

We need a design for what happens when the user doesn't have permission.

**Comment by pdpinch** [comment]
@giocalitri @mbertrand which APIs needs to be updated to honor these permissions?

**Comment by mbertrand** [comment]
General moira question: a typical moira user list looks like this:
```
['alicep','cjshaw','emello','ferdial', 'mattbert']
```
When logging in via Touchstone for the 1st time, an account is created where username = email, so 'mattbert@mit.edu'.  Is it safe to assume that the names in the moira list will always equal the prefixes of the emails before the '@'?

**Comment by mbertrand** [comment]
PS, this is the full moira list for 'odl-engineering' returned by mit-moira, there are many dupes and Anna is missing:
```
['alicep',
 'alicep',
 'cjshaw',
 'cjshaw',
 'emello',
 'emello',
 'ferdial',
 'ferdial',
 'gdimilia',
 'gdimilia',
 'gschneel',
 'gschneel',
 'gsidebo',
 'gsidebo',
 'ichuang',
 'kkirwin',
 'ktierney',
 'mattbert',
 'mattbert',
 'mriley',
 'nlevesq',
 'nlevesq',
 'pdpinch',
 'pdpinch',
 'robhouse',
 'robhouse',
 'rsikkema',
 'shaidar',
 'shaidar',
 'tmacey',
 'tmacey',
 'wld']
```

**Comment by pdpinch** [comment]
We can handle this as an enhancement, but I think Anna is missing because the  `list_member()` method of the mit-moira library only requests members of type `USER`. Because Anna is stored as an e-mail address, I think her type is `STRING`

https://github.com/mitodl/mit-moira/blob/master/mit_moira.py#L47

This case is a little bit outside of MVP, since we're focused on internal MIT usage, where everyone on the moira list should be a `USER` with a kerberos ID.

**Comment by mbertrand** [comment]
It looks like there are issues with the moira WSDL service itself.  The raw response from a direct call to it still does not contain Anna's account.

`mc.client.service.getListMembership('odl-engineering', 'USER', True, 10000, mc.proxy_id)`
```
[{
     'list': 'odl-engineering',
     'member': 'alicep',
     'type': 'USER'
 }, {
     'list': 'odl-engineering-platform',
     'member': 'alicep',
     'type': 'USER'
 }, {
     'list': 'odl-engineering',
     'member': 'cjshaw',
     'type': 'USER'
 }.....
```
Another option which may be actually better is to get all the moira lists that a particular user is on:
`mc.client.service.getUserListMembership('mattbert', 'USER',  True, 10000, mc.proxy_id)`
```
[{
     'isActive': '1',
     'isGroup': '1',
     'isHidden': '1',
     'isMaillist': '0',
     'isPublic': '0',
     'listName': 'exchange-acl'
 },...
```

However, nothing is returned when I use my MIT email instead of `mattbert`.  I could get results for Anna only when I used `annagav` and not her email address that listed for the odl-engineering list.  So what I suspect is happening is that the WSDL service only returns and accepts Kerberos ID's.

**Comment by mbertrand** [comment]
@pdpinch you're right, if I use 'STRING' I get Anna returned from the request and no one else.  So are you okay with just using 'USER' and leaving out the email addresses, or should the app make 2 calls, one each with 'USER' and 'STRING'?

**Comment by mbertrand** [comment]
Never mind, changing the type from `USER` to a blank string returns everyone

**Comment by mbertrand** [comment]
> which APIs needs to be updated to honor these permissions?

REST API:
`ui.views.VideoViewSet` 

Template views:
`ui.views.VideoDetail`
`ui.views.VideoUswitch`

**Comment by mbertrand** [comment]
Assumption: all videos are private.  Videos without moira_lists assigned will be viewable only by admins for the video's collection. TODO: Make a 'public' boolean field for videos to specify that they can be viewed by anyone - https://github.com/mitodl/odl-video-service/issues/156
