### ISSUE TITLE
request and install TechTV SSL cert for OVS application

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#535]

**Comment by shaidar** [comment]
Cert has been requested from IS&T (RT#4526319) and will be deployed once received.

**Comment by pdpinch** [comment]
@shaidar did we get the cert yet? If so, I think we should plan to do this when Matt is back.

**Comment by shaidar** [comment]
Yes. We got the cert and it's in vault. So the next time we run a deployment, it should get installed.

**Comment by pdpinch** [comment]
Did this get deployed with 0.17.1? Did 0.17.1 get deployed?

**Comment by shaidar** [comment]
Both `RC` and `Prod` are running `0.18.0` and have the new cert. Closing this issue.
