### ISSUE TITLE
Fix bars that show up on embedded videos (in blossoms etc)

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/odl-video-service#539]
When videos are embedded, there are visible bars on the page around the video, depending on the source of the video. There are three reasons for this.

1. The html on the blossoms site has the wrong size box for the video - The iframe in the blossoms site has a width of 544 and a height of 336. The height should be 306. We should probably just ignore this because it is a problem on their side.
2. Given that the box is the wrong size, a white bar shows up beneath the video. This bar is white because the body inside the iframe has a background that is white. We should make this background transparent. This will make the bar disappear.
3. The video itself has a max height of "calc(100vh - 200px)" and "calc(100vh - 60px)" for mobile. This css was intended for the video details page.  We should not have a max height for the embedded video html. So for the embedded video, remove the max-height.

**Comment by pdpinch** [comment]
Nice solutions. 

Can you go ahead and work on this? It would be nice to have these fixes in place before the DNS cutover.
