### ISSUE TITLE
make it deployable

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#54]
For CI and RC, it's OK to omit the Touchstone login, so we can use Heroku.

**Comment by giocalitri** [comment]
blocked by #66

**Comment by pdpinch** [comment]
What's blocking this now?

**Comment by giocalitri** [comment]
#78

**Comment by pdpinch** [comment]
#78 is closed now. Do we still have blockers?

**Comment by giocalitri** [comment]
CI and RC are working.
