### ISSUE TITLE
Not seeing expected analytics data in prod

### ISSUE THREAD

**Issue by adorsk** [mitodl/odl-video-service#545]
Per chat w/ @emmello on 2018-04-11.

This video shows analytics data:
 https://video.odl.mit.edu/videos/2981c67243fb47cdaa8a70c43287f2e6/

This video does not:
 https://video.odl.mit.edu/videos/0779337a56c34f85b6b8e5bc4ed55f18/

We expect both videos to have data.

My current suspicion is that it's related to multicam. The videos w/ multicam do have analytics data. But single-cam videos do not.

To check:
1. Are there events in GA for single-cam videos?
   1. if no, then our culprit is likely how we send GA events in the video player for single-cam videos.
   2. if yes...
2. Does our GA query retrieve data for single-cam videos?
   1. If no, this is our culprit.
   2. if yes...
3. What does the data look like coming back from our GA query?

**Comment by adorsk** [comment]
> Are there events in GA for single-cam videos?
Yes, there are events for both single-cam and multi-cam videos.

> Does our GA query retrieve data for single-cam videos?
No. It does retrieve data for multi-cam videos, but not for single-cam videos.

So the issue lies in the GA query for single-cam videos.
If the camera dimension (`dimension1`) is removed from the query's `dimensions` parameters, then the query *does* return data for single-cam videos.

Upon digging into the `VideoPlayer` code, it appears that the camera_dimension is set only for multi-cam videos:
https://github.com/mitodl/odl-video-service/blob/6317db2df5234d026a2cab15d6999c370745ae90/static/js/components/VideoPlayer.js#L320

This means that events for single-cam videos are sent w/out any dimension context, and thus are not included in our query results.

I can think of a few options to fix this:

A. Change `VideoPlayer` to always set a custom dimension.
   ```
PROS:
1. data schema will be the same for all videos.
CONS:
1. Old analytics for single cam videos (I think since 2017-10?) would no longer be includes.
   ```

B. Branch our backend GA query on whether a video is multiangle
   ```
PROS:
1. Preserves old analytics data for single cam videos.
CONS:
2. Have to support two different queries for video types (not really that a big a deal though)
   ```
C. Something else?

I suggest we go with B, so that we can keep the legacy data.

**Comment by pdpinch** [comment]
I agree. Let's go with B. 

Since the GA queries are kind of impenetrable, you should leave a comment about why there are two of them. 

> I suggest we go with B, so that we can keep the legacy data.
