### ISSUE TITLE
The current logout functionality needs to be changed or removed

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#56]
The logout link redirects to the admin logged out page, even when touchstone integration is enabled (see http://video.odl.mit.edu).  This behavior needs to change:

- Log out of Touchstone and redirect to Touchstone login page? (not sure if this is possible)
- Remove the logout link altogether?

**Comment by pdpinch** [comment]
IIRC, there's no way to log out of TouchStone. 

If possible, it would be nice to keep a logout button, for logging out of the video application.
