### ISSUE TITLE
112 TTV public TechTV videos whose subtitles couldn't be found

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#560]
In migrating public videos collections from TechTV, 112 failed due to missing subtitle files.

**Comment by pdpinch** [comment]
@emmello @mbertrand I believe this is blocking us from changing the DNS for TechTV to point to OVS. #440

**Comment by mbertrand** [comment]
Collections with videos that are missing subtitles: 4017 3982 3691 3304 3261 3198 3031 2650 2313 2257 2228 1936 1924 1882 1732 1651 1081 761 639 626 601 449 397 315 239 25 18 575

**Comment by mbertrand** [comment]
```
DROPBOX_TOKEN=<value>;DROPBOX_FOLDER=/Captions;MYSQL_PASSWORD=<value>

python manage.py techtvimport --user <mysql_user> --db <mysql_db> --host <mysql_host> --protected 0 --aws  --noyoutube 2228 --collections 2228 4017 3982 3691 3304 3261 3198 3031 2650 2313 2257 2228 1936 1924 1882 1732 1651 1081 761 639 626 601 449 397 315 239 25 18 575
```

**Comment by shaidar** [comment]
@mbertrand Are we waiting on anything or should I go ahead and run the import listed above again?

**Comment by mbertrand** [comment]
@shaidar you can go ahead and run the above command.

**Comment by shaidar** [comment]
Ran migration on `prod` and it completed successfully.

**Comment by mbertrand** [comment]
@emmello do you think the final 10 missing captions are a lost cause, or should we keep this issue open until they're all accounted for?

**Comment by emmello** [comment]
I'd give up on them.  I've searched high and low and the videos that have been posted on Youtube elsewhere don't have captions, so I don't think we need them here.  I'd say we're done with this. (unless someone wants to experiment with Amazon Translate to make some.)
