### ISSUE TITLE
14 missing Blossoms videos

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#566]
> There are 14 Blossoms that were uploaded since the last DB dump that haven't been ported over to OVS since it didn't know they were there.

**Comment by mbertrand** [comment]
After the MySQL database copy has been updated, this is the command to run:

```
DROPBOX_TOKEN=<value>;DROPBOX_FOLDER=/Captions;MYSQL_PASSWORD=<value>

python manage.py techtvimport --user <mysql_user> --db <mysql_db> --host <mysql_host> --protected 0 --aws --cloudfront 575 --collections 575
```

**Comment by pdpinch** [comment]
How/who will update the MySQL database?

**Comment by mbertrand** [comment]
Sar or Tobias
