### ISSUE TITLE
Don't require login for 404 errors 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#604]
e.g. https://techtv.mit.edu/collections/revisting-case aka https://video.odl.mit.edu/collections/revisting-case

**Comment by pdpinch** [comment]
I'm not sure if this is an issue for @mbertrand or @mitodl/devops

**Comment by emmello** [comment]
First link was a typo - it's http://techtv.mit.edu/collections/revisiting-case

**Comment by mbertrand** [comment]
I think Touchstone is configured to intercept all URL's that begin with `/collections`

**Comment by pdpinch** [comment]
We could remove that, as long as the collection template requires a logged-in user.

**Comment by mbertrand** [comment]
@blarghmatey @shaidar do you think it would be possible for Touchstone/Nginx to intercept only the `/collections(/)` URL and not `/collections/<collection_id>(/)`?

**Comment by mbertrand** [comment]
This will likely require:
- Changing the Touchstone configuration to intercept `/collections` and `collections?next=<redirect>` but not `collections/<collection_key`
- Changing the `CollectionReactView` to conditionally require login only if there is no collection key.

**Comment by blarghmatey** [comment]
Yeah, we can do that. We can also just set it up for /login or something like that.
