### ISSUE TITLE
Update 404 and 403 error to handle TechTV URLs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#617]
As a user who was following a TechTV link, it would be reassuring if the error message acknowledged that the collection and/or video I am looking for is no longer available. 

Current message: "This is a 404 error. This is not the page you were looking for."

Proposed new message: "This is a 404 error. This is not the page you were looking for. If you are looking for a video or collection, it is no longer available for viewing"

**Comment by pdpinch** [comment]
@mbertrand I see a PR for 404 errors, but none for 403. Do we ever return a 403?

**Comment by mbertrand** [comment]
The API will return a 403 for authenticated users that don't have permission to see a video.

<img width="696" alt="screen shot 2018-05-16 at 1 38 23 pm" src="https://user-images.githubusercontent.com/187676/40133697-7ef5c3b2-590e-11e8-824c-fc70e0495041.png">

**Comment by pdpinch** [comment]
I think that's good enough -- although the line breaks are awkward
