### ISSUE TITLE
Email notifications to users on video status updates

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#64]
Users should be notified by email (with the option of turning these notifications off) when their videos have completed transcoding or have failed to either upload or transcode.  The notifications should include a user-friendly description of what the problem was if a failure occurred ('Your selected file could not be retrieved from Dropbox', 'Your file does not appear to be in a compatible video format', etc.)

The e-mail should include a link for the user to take appropriate action. If the transcode was successful, the link should go to the video detail page so the user can view the video and share it.

**Comment by pdpinch** [comment]
We can reserve turning notifications off for a future issue.

**Comment by giocalitri** [comment]
> 'Your file does not appear to be in a compatible video format'
how do we know this?

> The e-mail should include a link for the user to take appropriate action.
What are the possible actions? Just delete the video object?

**Comment by mbertrand** [comment]
> how do we know this?

Based on the details in the transcode job output, in this case it would be something like:
`"StatusDetail":"4000 aa2e0e30-b1d3-4fcc-94b5-efbc76efbabd: Amazon Elastic Transcoder could not interpret the media file.`

>What are the possible actions? Just delete the video object?

If the upload or transcode failed, provide users with the option to try again on the video detail page #69

**Comment by giocalitri** [comment]
@pdpinch do I need to process the errors according to this document to send meaningful errors to the user?
http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/error-handling.html#api-error-codes

**Comment by pdpinch** [comment]
I think I'd like to send the error `message` (from the JSON response) to the user in the email and then log (at least) the HTTP status code and the `x-amzn-ErrorType`

It would be nice to be able to override certain error codes with an even more human-readable error than the message, but I don't know what our messages would be yet, until we get some more experience. 

Does that make sense?

**Comment by giocalitri** [comment]
The idea to deal with the ET error is:

- if the error code is NOT in the 4000s, send an email telling the user something like: "We have had a problem the the processing the file: someone has been notified and we will follow up with you"
- if the error code is in the 4000s, send an email telling the user something like: "We have had a problem the the processing the file: please check if the file you uploaded is an actual video and you can play it. If you think it should work, please contact us at <email here>"

**Comment by pdpinch** [comment]
Draft e-mail messages at https://goo.gl/FpmQRb

**Comment by giocalitri** [comment]
who should we send the email(s) to? Currently I can use the Channel owner, but as soon as we implement moira lists we will not have any knowledge of who is uploading the video. 
Should we send it to all the members of the moira list "admin" channel group at that point?

**Comment by pdpinch** [comment]
As we discussed, moira groups also function as mailing lists, so if there are one or more moira lists associated with a collection, we will mail them all, in addition to the collection owner. (In my experience, the MIT mail server de-dupes the to list, so users shouldn't get duplicate mailings)

Since the collection admin list doesn't exist on the collection model yet (right?), you can open an issue to update this behavior after #52 is closed.

**Comment by giocalitri** [comment]
> In my experience, the MIT mail server de-dupes the to list, so users shouldn't get duplicate mailings

does this mean that I need to send a single email to all the addresses instead of one email per address?

**Comment by pdpinch** [comment]
If you can send one e-mail to all the address, I think that would be preferable.
