### ISSUE TITLE
No moira lists are returned for collaboration accounts with `mit.edu` emails 

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#646]
Users with Touchstone collaboration accounts and `mit.edu` email addresses are incorrectly assumed to be Kerberos accounts, so queries to the Moira server are passed a parameter of `type=USER` instead of `type=STRING`, and no matching moira lists are returned.

**Comment by pdpinch** [comment]
MIT doesn't allow creation of new Touchstone collaborator accounts any more, so this is (mostly) moot.
