### ISSUE TITLE
Lots of OSError sentry messages from video downloads

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#651]
This is likely caused by users canceling downloads before completion, and/or perhaps temporary recoverable breaks in the connection during download.  Used to happen frequently with requests to the moira server before caching was put in place.

@blarghmatey @shaidar what do you think of [switching on on `disable-write-exception` in the uwsgi config](https://github.com/pypa/warehouse/issues/679#issuecomment-339387108)?

**Comment by mbertrand** [comment]
https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/349208356/activity/

**Comment by shaidar** [comment]
Deployed to RC and Prod
