### ISSUE TITLE
Add type-ahead filter to Moira list selection dropdown

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/odl-video-service#652]
On the Change collection page in django admin, when you want to add a moira list to a collection, currently the user has to scroll through a long list to find the desired list.

The proposal is to add a typeahead filter to the dropdown so the user can type the list name to filter the list. 

See mocks below:

![image](https://user-images.githubusercontent.com/20047260/41548681-aa4ab642-72f1-11e8-9163-812634fdfe4d.png)

![image](https://user-images.githubusercontent.com/20047260/41548693-af497584-72f1-11e8-9843-7a18cf7fb2c4.png)

![image](https://user-images.githubusercontent.com/20047260/41548703-b66694e6-72f1-11e8-9467-cc98e6dc0b4b.png)

**Comment by pdpinch** [comment]
@mbertrand do you know if there's any built-in django way to do this?

**Comment by mbertrand** [comment]
@pdpinch There is a django plugin for doing this, but it requires modifications to the current admin UI.  I did some preliminary testing with it about a month ago, here's a screenshot:

<img width="1187" alt="screen shot 2018-07-03 at 9 29 31 am" src="https://user-images.githubusercontent.com/187676/42222607-a720fff4-7ea3-11e8-85ef-9978e682ca88.png">

**Comment by pdpinch** [comment]
What's the name of the plugin?

The UI change seems fine, as long as it doesn't require a model change.

**Comment by mbertrand** [comment]
[django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light)

**Comment by amir-qayyum-khan** [comment]
Django 2.0 has it https://docs.djangoproject.com/en/2.0/releases/2.0/#django-contrib-admin.
Should we upgrade django version?

**Comment by pdpinch** [comment]
@noisecapella did you do some research on what the django 2.0 upgrade requires? (maybe not in this project, but one of the others?)

@mbertrand what do you think?

**Comment by mbertrand** [comment]
@pdpinch we will need to upgrade eventually.

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops i need settings `.env` for this project for this task.

**Comment by mbertrand** [comment]
@amir-qayyum-khan I will send you settings on keybase, for OVS I use the same AWS S3-related settings as on heroku ovs-ci
