### ISSUE TITLE
Analytics no longer showing on OVS videos

### ISSUE THREAD

**Issue by emmello** [mitodl/odl-video-service#658]
Sometime after the semester ended, GA stopped reporting to OVS.:

![image](https://user-images.githubusercontent.com/1099800/42042693-c0ca604c-7ac2-11e8-83ca-a6471f500727.png)

Analytics are still being logged in GA.

**Comment by pdpinch** [comment]
probably caused by #657

**Comment by pdpinch** [comment]
Sentry issue: [ODL-VIDEO-SERVICE-60](https://sentry.io/mit-office-of-digital-learning/odl-video-service/issues/528140533/)

**Comment by pdpinch** [comment]
Oops. Wrong Sentry issue.

**Comment by mbertrand** [comment]
`GA_KEYFILE_JSON` was being stripped of double-quotes on deployment, fixed now.
