### ISSUE TITLE
Interpret errors from transcode/upload jobs to be more user-friendly

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#70]
When an error occurs during an upload or transcode job, display a user-friendly interpretation of that error to the user while reporting and/or storing the raw error/exception message for dev troubleshooting if necessary.

**Comment by mbertrand** [comment]
Add 'error_raw' and 'error_message' fields to the Video model. 'error_raw' will contain the literal error message, such as:
4000 f5c7bdf7-0776-4a0b-bbb0-922cb3b1ee67: Amazon Elastic Transcoder could not interpret the media file.
and the error_message is what will be displayed to the user:
The video file could not be processed. It may be corrupt or in an incompatible format.

**Comment by pdpinch** [comment]
@mbertrand @gsidebo I think this is done?

**Comment by mbertrand** [comment]
yes, done.
