### ISSUE TITLE
Collection page: default sort to creation date, descending

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#700]
As a user, I'd like to have the most recent videos at the top of the page. 

Ideally, I'd like to be able to control the sort. But sorting by creation date descending is the best default option.

**Comment by mbertrand** [comment]
@pdpinch this should already be the case, are there certain collections where you've seen a different order?

**Comment by pdpinch** [comment]
@mbertrand is there a way we could solve a sort that came out like this one:

https://video.odl.mit.edu/collections/c8641249aa824552b801bcb055eccd8b/

**Comment by mbertrand** [comment]
@pdpinch The videos were uploaded out of order, we would need to manually modify their creation dates: https://video.odl.mit.edu/admin/ui/video/?q=MIT-6.003-2017-Fall-L01

**Comment by pdpinch** [comment]
Although the admin displays the creation date, it doesn’t allow you to change it.

**Comment by mbertrand** [comment]
It would have to be done via python shell.

**Comment by pdpinch** [comment]
This is moot, now that #727 merged
