### ISSUE TITLE
Display user-friendly error message in the video player

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#71]
If the video player cannot play a video for some reason (lost connection, bad URL, etc), display a user-friendly message.

**Comment by pdpinch** [comment]
@mbertrand what's the status of this?

**Comment by mbertrand** [comment]
@pdpinch Nothing new as far as I know - if the video has transcoded successfully but for some reason an error happens on playback, the standard videojs (or uswitch) behavior will occur.  I compared to Youtube and there doesn't seem to be any special error handling there either.

Here's what happens at the moment, along with Youtube for comparison:

- Scenario 1: The playlist can't be loaded due to bad connection/url:
  - VideoJS: endless spinning circle on black screen.
  - Uswitch: black screen showing only the video title.
  - Youtube: endless spinning circle on black screen.

- Scenario 2: The video starts playing but loses connectivity:
  - VideoJS: video stops, displaying the last frame available. No error message.  Continues trying to reconnect to the last resolution video indefinitely.
  - Uswitch: video stops, displaying the last frame available. No error message. Tries to connect to the playlist for each of the 4 resolutions available 5x then quits.
  - Youtube: video stops, displaying the last frame available along with a spinning circle. Continues trying to reconnect indefinitely.

**Comment by roberthouse54** [comment]
It does not seem like youtube has a much better implementation for this than we do currently.

**Comment by pdpinch** [comment]
We're over-achieving if YouTube doesn't do this either.
