### ISSUE TITLE
add a custom_order field to allow sorting of Videos

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#726]
As a collection owner, I'd like to be able to control the order of videos on the collection page.

Currently the order is determined by Video creation date, descending. This is good in most cases, but sometimes lecture uploads are missed and then uploaded late. When this happens, they appear out of order. 

### acceptance criteria:
- [ ] add a `custom_order` field to the Video model
- [ ] expose the `custom_order` field in the django admin 

### related issues (out of scope)
- front-end UI for re-ordering videos in a collection

**Comment by mbertrand** [comment]
Can make the default sort order for the `Video` model based on the new field first, creation date second.  That way it wouldn't need to be unique and if videos have the same value (or no value) then creation date would be used instead.
`ordering = ['custom_order', '-created_at']`

**Comment by pdpinch** [comment]
@mbertrand does this mean that if Elaine sets the custom order field in the admin, it will change the behavior of the collection page?

**Comment by mbertrand** [comment]
Yes, it should change the video order on the collection page:  Videos with a non-null custom_order should be displayed first, from lowest to highest custom_order value, followed by videos without a custom_order, in reverse chronological order. If two videos have the same custom_order value, they should be sorted in reverse chronological order relative to each other.
