### ISSUE TITLE
Filter out invalid data from video analytics

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#728]
At least one plugin ("Youtube Video Downloader") seems to send bad data to google analytics, resulting in values other than "camera1" through "camera4".  These should be filtered out.

**Comment by pdpinch** [comment]
Did we always set the value to "camera1" through "camera4"? I'm wondering if we were deliberately loose with the matching to deal with some bad historical data of our own.

**Comment by mbertrand** [comment]
It used to differ slightly, I think we might have used numbers 0 to 3 at one point.
