### ISSUE TITLE
Use flowplayer instead of video.js

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#73]
- We will need to download the commercial version
- repackage from zip to tgz
- make available online (on s3?) with a persistent URL
- handle versioning (in filename?)
- yarn add <URL>

This should resolve the webpack prod issue. #66

**Comment by mbertrand** [comment]
@pdpinch should this be closed?

**Comment by pdpinch** [comment]
Yeah. No plans to use FlowPlayer now.
