### ISSUE TITLE
amps-web redirects

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#737]
from time to time, we have gotten mail from users trying to track down videos that were once hosted on amps-web.amps.ms.mit.edu. In particular, [these videos from 6.045 that are linked from Stellar](http://stellar.mit.edu/S/course/6/sp15/6.045/special/videos/index.html).

All these videos are on OVS. To cut down on user support time, we can create custom redirects. A list of URL mappings in available at https://docs.google.com/spreadsheets/d/1OJaKmjd0alvnombPekT0j-aiCmQ4JdjlOOcpV9luTTs/edit#gid=0

**Comment by blarghmatey** [comment]
@shaidar I think this was already done. Can you verify and close this issue if completed?

**Comment by shaidar** [comment]
Changes deployed and randomly verified
