### ISSUE TITLE
Add REST API views for checking moira list membership

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#739]
Add views for determining:

- [ ] The members of a moira list (`/api/v0/moira/list/<list_name>`)
- [ ] The moira lists a user belongs to (`/api/v0/moira/user/<user_name or email>`)

These views should only be accessible to admins.

**Comment by tasawernawaz** [comment]
@mbertrand Could you please some context to it.

**Comment by mbertrand** [comment]
`/api/v0/moira/list/<list_name>` - return a list of users obtained via `ui.utils.get_moira_client().list_members(<list_name>)`

`/api/v0/moira/user/<user_name or email>` - return a list of moira lists obtained via `ui.utils.query_moira_lists(<user>)`

**Comment by mbertrand** [comment]
To make this easier to use, since >90% of usernames end with `@mit.edu`,  I think the `@mit.edu` could be left out of the supplied username for for `/api/v0/moira/user/<user_name or email>` URL, and the API should assume that it ends with `@mit.edu` when it does a lookup for the user.  For instance, if the URL is `/api/v0/moira/user/lskywalker`, it will look for a user with either username or email of  `lskywalker@mit.edu`, but if the URL is `/api/v0/moira/user/lskywalker@touchstone.com` it will look for a user with username or email of  `lskywalker@touchstone.com`.
