### ISSUE TITLE
embedded videos in Residential MITx from video.odl.mit.edu not playing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#740]
from [ZenDesk #26917](https://odl.zendesk.com/agent/tickets/26917)

> Students in 6.036 are reporting spinning play wheels, when trying to play videos embedded with an iframe from video.odl.mit.edu ; this error appears in the js console:
> 
```
VM606 www-widgetapi.js:100 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://video.odl.mit.edu').
```
> 
> for example, due to this embed:
> 
```
<iframe src="https://video.odl.mit.edu/videos/0a4d3a43a8524616a2e027852808aed0/embed/" width="560" height="315" frameborder="0" allowfullscreen="1"></iframe>
```
> 
> Example which reproduces the error:
>
> https://lms.mitx.mit.edu/courses/course-v1:MITx+6.036+2019_Spring/courseware/Week6/week6_video/1
>
> Playing directly at the video.odl.mit.edu site still works, as a backup.

**Comment by mbertrand** [comment]
This issue is described in the VideoJS-Youtube plugin [here](https://github.com/videojs/videojs-youtube/issues/532), and a potential solution is on [StackOverflow](https://stackoverflow.com/questions/54786686/videojs-youtube-video-not-playing-in-an-iframe-in-desktop-chrome).
