### ISSUE TITLE
allow sharing of HLS streaming URL on specifed collections

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#754]
Part of https://github.com/mitodl/mitxpro/issues/16

As an open edX course author, I'd like to be able to get the HLS streaming URL for my video, so I can paste it into a video xBlock on open edX. 

### acceptance criteria

- [ ] add a boolean field to collection model `allow_share_openedx` 
- [ ] display the boolean field in the collection admin
- [ ] if `allow_share_openedx` is true, display the full URL for the video's HLS video file when a collection owner clicks the share button in a "open edX Video URL" box, similar to the existing one for "Video URL". For example, for the URL at https://video.odl.mit.edu/videos/05abcf60f486410bbbb6cbf06463898c/ the open edX Video URL would be https://d3tsb3m56iwvoq.cloudfront.net/transcoded/05abcf60f486410bbbb6cbf06463898c/video__index.m3u8

**Comment by mbertrand** [comment]
Seems reasonable.  One concern is how long we can count on this URL working in edX since it's not on the list of accepted formats.

**Comment by pdpinch** [comment]
> One concern is how long we can count on this URL working in edX since it's not on the list of accepted formats.

@mbertrand I've seen that message from edX about accepted formats, but I forget where. Can you point me to it, because I think it should be updated.

**Comment by mbertrand** [comment]
I think it is on the form where the user would paste this URL for the video.
