### ISSUE TITLE
Secrets cannot be in file

### ISSUE THREAD

**Issue by giocalitri** [mitodl/odl-video-service#78]
We do not have a way in heroku to load secrets from files, so we  need to move everything to environment variables.

**Comment by mbertrand** [comment]
Maybe one of these options might work for getting the secrets files on Heroku?

- https://github.com/heroku/heroku-builds: `Create build from local dir` option
- https://devcenter.heroku.com/articles/dropbox-sync

**Comment by mbertrand** [comment]
http://www.beardedhacker.com/blog/2014/10/20/load-private-key-to-heroku/

**Comment by giocalitri** [comment]
> http://www.beardedhacker.com/blog/2014/10/20/load-private-key-to-heroku/

well, this is exactly what I meant, but the problem is that we need to modify the code to read from env variables and not from the file.

**Comment by mbertrand** [comment]
The Moira API only accepts file paths for the x509 certificate/private key: https://mit-moira.readthedocs.io/en/latest/

**Comment by giocalitri** [comment]
I guess we have in our roadmap an issue to fork Moira client code, then...
