### ISSUE TITLE
FEATURE_RETRANSCODE_ENABLED .env value

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#794]
#### Summary

Describe where/how to generate these new values

`FEATURE_RETRANSCODE_ENABLED=True`

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by mbertrand** [comment]
Related to #792

**Comment by pdpinch** [comment]
Can this be closed now?

**Comment by shaidar** [comment]
Done
