### ISSUE TITLE
Secrets for different environments

### ISSUE THREAD

**Issue by giocalitri** [mitodl/odl-video-service#81]
We need the following secrets for the different environments (`dev`, `ci`, `rc`, `prod`).

Dropbox:

- for the `dev` we can use an app created with personal accounts, but we need apps for the other environments created with a "MIT ODL" account. 
- we need to apply to "Apply for production" for the `prod` app

AWS:
- we need AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for each environment (I am not sure if we can reuse the same for the different environments)

Cloudfront:
- we need a private key, a key id and a distribution id (I am not sure if we can reuse the same for the different environments)

S3: 
- we need buckets names different at least for production.

Elastic Transcoder
- we need a specific ET_PIPELINE_ID for an ET pipeline for each set of new buckets we create for S3

**Comment by giocalitri** [comment]
cc @pdpinch @blarghmatey

**Comment by pdpinch** [comment]
@shaidar @mbertrand has this been taken care of already?

**Comment by shaidar** [comment]
@pdpinch 
- [x] AWS
- [x] S3
- [x] Elastic Transcoder
- [x] CloudFront
  - CloudFront only allows for the creation of two keys so we're using one for prod and a different one for rc and ci
