### ISSUE TITLE
Order encode presets from highest to lowest 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#810]
Some video players (like the edX player) default to the first bitrate in the m3u8 playlist. This means that users on high-bitrate connections will start playing the lowest quality video and never have reason to request a better video. 

The OVS player has code to always choose the highest bitrate. 

We should change the settings to be highest bitrate to lowest.

**Comment by pdpinch** [comment]
We've recently discovered that this issue also affects the OVS player when used in Chrome. So it's worth fixing for all videos, not just xPRO videos.

**Comment by pdpinch** [comment]
https://github.com/mitodl/salt-ops/pull/1084 addresses this issue going forward, but we need to retroactively update the existing playlists. 

Although we could just re-encode all the videos, it would be more cost effective to just re-order the items in the `video__index.m3u8` files.

**Comment by mbertrand** [comment]
@pdpinch are you sure you want to do this to all videos?  I can't reproduce the Chrome behavior described above, the highest resolution plays by default for me on both OSX and Windows 10.

**Comment by pdpinch** [comment]
Is there a downside to doing it for all video? 

Elaine has reported incorrect playback in Chrome Windows, but I’m not 100% sure this is a fix. 

> @pdpinch are you sure you want to do this to all videos? I can't reproduce the Chrome behavior described above, the highest resolution plays by default for me on both OSX and Windows 10.

**Comment by mbertrand** [comment]
Might as well do all videos just to make them consistent
