### ISSUE TITLE
ENABLE_VIDEO_PERMISSIONS env setting

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#852]
#### Summary

Describe where/how to generate these new values

- `ENABLE_VIDEO_PERMISSIONS` - True

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production (after latest RC is merged)

**Comment by shaidar** [comment]
Deployed
