### ISSUE TITLE
Video keyboard control

### ISSUE THREAD

**Issue by annagav** [mitodl/odl-video-service#854]
Need to add keyboard support for the video lectures.

Here are the possible controls avaialble:

- [ ]  Space bar toggles play/pause.
- [ ] - Right and Left Arrow keys seek the video forwards and back.
- [ ] - Up and Down Arrow keys increase and decrease the volume.
- [ ] - M key toggles mute/unmute.
- [ ] - F key toggles fullscreen off and on. (Does not work in Internet Explorer, it seems to be a limitation where scripts cannot request fullscreen without a mouse click)
- [ ] - Double-clicking with the mouse toggles fullscreen off and on.
- [ ] - Number keys from 0-9 skip to a percentage of the video. 0 is 0% and 9 is 90%.

**Comment by pdpinch** [comment]
How do we turn these on? Do we need to add a plugin?

**Comment by annagav** [comment]
yes, we need a plugin. Could you select the controls you think are required for this issue?

**Comment by pdpinch** [comment]
I think we'd want all of these. 

Is there any more explanation of what "seek" means? I think the user request was to be able to jump ahead or back some number of seconds. Seek might be good enough, but I'm not sure.
