### ISSUE TITLE
Migrate raven-python to sentry-sdk

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/odl-video-service#868]
The `sentry-sdk` package is a replacement for `raven-python`, so raven should be replaced.

My immediate concern is adding structlog to the project for better logging, and we've been [encountering issues getting log messages not to be duplicated in Sentry](https://github.com/mitodl/odl-video-service/pull/865). We should make sure that `sentry-sdk` is in place before spending more time on troubleshooting message formatting.

**Comment by mbertrand** [comment]
@pdpinch if it's okay with you, I'm willing to start on this today.
