### ISSUE TITLE
Videos uploaded to OVS aren't being posted to xPRO Studio

### ISSUE THREAD

**Issue by shaidar** [mitodl/odl-video-service#927]
### Steps to Reproduce

We upload video into xPRO's studio via the method described In https://github.com/mitodl/mitxpro/issues/540. 

This was implemented in ODL Video Service (OVS) in https://github.com/mitodl/odl-video-service/pull/763 and refined in https://github.com/mitodl/odl-video-service/issues/765 

However, it looks like that stopped functioning in Koa. Now when we try to add a video to studio by posting to /api/val/v0/videos/ nothing happens. 

### Potential Solution

The Openedx endpoint `/api` requires JWT tokens and the [video task](https://github.com/mitodl/odl-video-service/blob/master/ui/api.py#L63) is using a Bearer token. The function needs to be changed to use JWT tokens instead.

### Expected Behavior

Video is listed in xPRO studio

### Actual Behavior

API call to Openedx fails and throws a 401 error

### Stacktrace

`HTTP/1.1 401 Unauthorized
Server: nginx
Date: Wed, 03 Feb 2021 14:06:15 GMT
Content-Type: application/json
Content-Length: 58
Connection: keep-alive
WWW-Authenticate: JWT realm="api"
Allow: GET, POST, HEAD, OPTIONS
X-Frame-Options: DENY
Vary: Accept-Language, Origin, Cookie
Content-Language: en`

### Related Issues

[Issue#2107](https://github.com/mitodl/mitxpro/issues/2107)

### Screenshot or Screencast

(Optional)

**Comment by pdpinch** [comment]
I'm surprised that we don't get a strong error in the OVS logs from this. We should make sure that if the post is failing with a 401 that it gets logged and we raise an issue to Sentry.

**Comment by shaidar** [comment]
I think the wording is a bit misleading on the task:
`[2021-02-02 22:11:06,969: INFO/ForkPoolWorker-3] Task ui.tasks.post_hls_to_edx[fa011226-cf1d-4023-b52c-f0f0a8210c59] succeeded in 0.1703745573759079s: [('https://courses-rc.xpro.mit.edu/api/val/v0/videos/', 401)]`

It does raise a [Sentry error](https://sentry.io/organizations/mit-office-of-digital-learning/issues/2194866695/?project=194353&query=is%3Aunresolved) though.

**Comment by pdpinch** [comment]
@annagav @mbertrand looks like this didn't work. As [@shaidar said in Slack](https://mitodl.slack.com/archives/G5T80SA7L/p1612380305034100), we need to go through the whole JWT lifecycle with edX, not just change the header. 

[edX has some documentation on how to do this](https://course-catalog-api-guide.readthedocs.io/en/latest/authentication/), but it is a standard OAuth pattern I believe.
