### ISSUE TITLE
Support USwitch player as an alternative to Video.js

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#93]
Part of Lecture Capture Epic

The Lecture Capture feature uses a different video player which has the ability to mimic the playback of 4 synchronized video streams. This allows the user to "choose" between viewing the instructor, the chalkboard or either of two other video sources. (need example link)

This player may come with license restrictions which limit us to hosting it on an mit.edu domain

### Acceptance criteria:
- [x] Update this ticket once we determine if this is called the Unity player or the Omniplayer
- [x] The choice of player should be set at the video level. 
- [x] The video player template should import the chosen player (presumably via `<script>` tag)
- [x] Support the custom Omni/Unity Player playlist format (if necessary)
- [x] We want to continue to allow channel admins to upload their own video to a channel that will play with the standard video.js

###  Questions:
- [x] What is the player actually called, in the code we have licensed?
- [x] Do we need to make changes to the VideoObject model in order to support the custom playlist format?

**Comment by Ferdi** [comment]
- Are we sure video.js cant display these videos.
- It seems too restrictive to make the player based on the collection and not individual video

**Comment by mbertrand** [comment]
- In the code itself it's called `OmniPlayer`; that's also the name of the HTML page and title in LectureCapture links, for example `http://amps-web.amps.ms.mit.edu/courses/1Bplayer-2015aug14/OmniPlayer.html`

- The latest version in the shared Dropbox folder can play HLS files.  
- The menu bar in the latest version is different: 
  - Playback speed control is accessed by clicking on the gear icon, and has fewer options (0.25x - 4x, compared to 0.25 - >60x)
  - The thumbnail location switcher moves the video thumbnails from inside the player to its own window (old player - from top to bottom of player).

**Comment by mbertrand** [comment]
@ferdi The base video.js player cannot switch between scenes like OmniPlayer can.  I found some video.js plugins that are somewhat relevant, but they would have to be forked/modified to recreate the same functionality:
- https://github.com/xbgmsharp/videojs-rotatezoom
- https://github.com/danielcebrian/rangeslider-videojs

**Comment by mbertrand** [comment]
Example link: http://amps-web.amps.ms.mit.edu/courses/6/6.046/2017spring/L01/rspnsv/MIT-6.046-lec-mit-0000-2017may19-1901-L01/

**Comment by pdpinch** [comment]
FYI, after discussing with Ferdi, we deicded that the choice of video player should be set per video, not per channel. This will give us more flexibility if faculty want to add ad hoc videos to an existing course channel. And it doesn't interference with automation, since we'll be scripting the create of video objects for lecture capture anyway. 

I updated the description to reflect this.

**Comment by mbertrand** [comment]
The official name is `USwitch` in the US (OmniPlayer in France).

**Comment by mbertrand** [comment]
@pdpinch is the 'custom Omni/Unity Player playlist format' an extra feature that is currently supported by LectureCapture?

**Comment by pdpinch** [comment]
Not at all. I just wanted to make sure the USwitch player didn't require a different type of playlist/manifest. I'm happy to hear that it uses the same HLS manifest as Video.js.

**Comment by mbertrand** [comment]
I added a `multiangle` boolean attribute to the Video model (False -> used video.js, True -> use USwitch)
