### ISSUE TITLE
endpoint for creating video objects

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#94]
Part of the Lecture Capture Epic

In order to automate the processing of lecture capture videos, we need a REST endpoing that will be called by the 1Beyond Lecture Capture machines when a capture is completed. The endpoint will allow a script to create a video object in OVS and start the transcoding process. 

### acceptance criteria 
- [ ] shared secret authentication (?)
- [ ] need an API spec which includes a collection name, video name and the file location (?)

### questions
- [ ] Is a shared secret sufficient for authentication?

**Comment by Ferdi** [comment]
I thought  OVS does not directly talk to 1beyond. Instead  1 beyond pushes to S3 and OVS talks to S3.

Maybe @blarghmatey @giocalitri  can summarize our discussion here.

**Comment by pdpinch** [comment]
Replaced by #100
