### ISSUE TITLE
S3 keys should also contain username, video pk and maybe env

### ISSUE THREAD

**Issue by giocalitri** [mitodl/odl-video-service#99]
Given that we currently use the same buckets for multiple environments, it is pretty difficult to visually understand which file belongs to which environment

**Comment by pdpinch** [comment]
@shaidar what are you thoughts on this?

**Comment by shaidar** [comment]
Given that the transcoding pipeline requires one to use separate buckets as opposed to using folders in the same bucket, we will need to have separate ones for the different environments. Ideally we'd go with something like:
- odl-video-service-thumbnails-ci
- odl-video-service-transcoded-ci
....
Not exactly sure what the username and video pk refer to.

**Comment by pdpinch** [comment]
Not an issue any more
